### ISSUE TITLE
Is there OVMF-1920x1080.fd?

### ISSUE THREAD

**Issue by hexiangdong2017** [foxlet/macOS-Simple-KVM#1]
My Computer screen is 1920x1080

**Comment by tkoham** [comment]
Just edit config.plist in the clover esp as described here:

https://passthroughpo.st/new-and-improved-mac-os-tutorial-part-1-the-basics/

**Comment by schittler** [comment]
To note, because I had issues with this, detaching all disks and exiting from UEFI shell is the more reproducable way I found to get into OVMF config. It didn't seem to like F1/F2/DEL with anything bootable attached.

**Comment by zmo2s** [comment]
I get the same problem i did  in few step  :
 1 - run your vm
 2 - download clover configurator https://mackie100projects.altervista.org/download-clover-configurator/ 
 3 - open clover configurator choose efi partition  of your os(for me apple) between 200 and 256 Mb
 4-  Edit the the file config.plist in folder CLOVER in your partition efi, change GUI resolution for me that was 1280x 720 so i change to 1920x1080
