### ISSUE TITLE
Cannot install Xcode

### ISSUE THREAD

**Issue by Yul3n** [foxlet/macOS-Simple-KVM#10]
Hardware:
ryzen5 2400g 
16go RAM

**Comment by foxlet** [comment]
I'll be checking on this in a bit.

**Comment by mdillavou** [comment]
What is the solution to this? When in the App Store, I can search for XCode, but the button to download it is grayed out.

**Comment by audkar** [comment]
Yes. Same issue here. If anyone could share solution how to deal with this. It would be great

**Comment by foxlet** [comment]
Have you tried https://download.developer.apple.com/Developer_Tools/Xcode_10.2.1/Xcode_10.2.1.xip ?

**Comment by mdillavou** [comment]
downloading xcode directly worked for me. I am not sure why that app store doesn't though.

**Comment by foxlet** [comment]
Too many users have been using the default serial number, so I think Apple's APIs have reached the single-machine limit.

**Comment by fernando-jascovich** [comment]
I think this issue is related to Catalina-beta version. In any case, downloading it directly from https://developer.apple.com/download/ solves it.

**Comment by pi2in3** [comment]
i want Catalania but mojave downloaded every time :
[ho3in@fedoraGnome macOS-Simple-KVM-master]$ ./jumpstart.sh --catalina
Requirement already satisfied: requests in /usr/lib/python3.7/site-packages (from -r requirements.txt (line 1)) (2.21.0)
Requirement already satisfied: click in /home/ho3in/.local/lib/python3.7/site-packages (from -r requirements.txt (line 2)) (7.0)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/lib/python3.7/site-packages (from requests->-r requirements.txt (line 1)) (3.0.4)
Requirement already satisfied: idna<2.9,>=2.5 in /usr/lib/python3.7/site-packages (from requests->-r requirements.txt (line 1)) (2.7)
Requirement already satisfied: urllib3<1.25,>=1.21.1 in /usr/lib/python3.7/site-packages (from requests->-r requirements.txt (line 1)) (1.24.3)
2019-07-22 18:09:25,745 Network Request: Fetching https://swscan.apple.com/content/catalogs/others/index-10.15seed-10.15-10.14-10.13-10.12-10.11-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog
2019-07-22 18:09:35,531 Selected macOS Product: 041-88929
Fetching BaseSystem/BaseSystem.dmg ...  [------------------------------------]    1%  00:12:30^C
