### ISSUE TITLE
Are There Plans To Provide An OpenCore Image?

### ISSUE THREAD

**Issue by CuriousTommy** [foxlet/macOS-Simple-KVM#100]
While Clover will still receive support for a while, it seems that some Hackintosh developers want to focus on OpenCore only. Plus it has some nice features that Clover doesn't have.

It might be a good idea to add OpenCore boot image as an additional option until OpenCore completely replaces Clover.

**Comment by foxlet** [comment]
No.

**Comment by CuriousTommy** [comment]
@foxlet As in never, or not any time soon?

**Comment by foxlet** [comment]
If Clover dropped support, it would be more likely that it's removed and functionality integrated into firmware. Clover is not actually required and mainly there for ease-of-use (the config is very minimal).

**Comment by CuriousTommy** [comment]
Oh I didn’t know that Clover is not really required. Thank you for the explanation.
