### ISSUE TITLE
No clipboard integration

### ISSUE THREAD

**Issue by arrrlaska** [foxlet/macOS-Simple-KVM#102]
(Not complaining, just wanted to word the issue as an *issue*).

I understand that clipboard integration requires a guest utility. Is there not one for MacOS, or any other tricks that might work for the clipboard?

**Comment by foxlet** [comment]
I've used Synergy (or the open source Barrier fork) for the purposes of sharing the clipboard and input devices.

**Comment by arrrlaska** [comment]
Sounds like a plan, thank you.

Have you used the vm for iMessage? I've had very mixed results, with it often falling back to sending texts instead of "blue bubble" iMessages.
