### ISSUE TITLE
jumpstart script downloads Catalina instead of Mojave

### ISSUE THREAD

**Issue by nmeln** [foxlet/macOS-Simple-KVM#103]
`./jumpstart.sh --mojave ` downloads Catalina dmg

**Comment by yoolsylva** [comment]
yes, i get same issue here, always download Catalina dmg

**Comment by win98se** [comment]
Now it downloads High Sierra dmg instead. 🤣

Workaround:
1. Download [this file](https://raw.githubusercontent.com/kholia/OSX-KVM/master/fetch-macOS.py) and put it with the same directory as `jumpstart.sh`, `basic.sh`, `make.sh` and `headless.sh`.
2. Run it and select your preferred dmg.
3. Use `dmg2img` or `qemu-img` to convert the downloaded `BaseSystem.dmg` to img format.

**Comment by Pilo11** [comment]
https://github.com/foxlet/macOS-Simple-KVM/pull/105
