### ISSUE TITLE
GPU Passthrough still uses only 5MB Max

### ISSUE THREAD

**Issue by 2JJ1** [foxlet/macOS-Simple-KVM#104]
Clicking the Apple logo at the top left then clicking the about button, it says that only 5MB is being used. It seems fairly accurate too considering anything even remotely graphic intensive like Google Chrome lags the machine like crazy.

I'm passing through a GTX 2070 on MacOS Catalina. I'm aware that the 20 series are not yet supported, but considering it is outputting video at all on the connected monitor, this makes me think this just means no drivers for features such as ray tracing.

**Comment by foxlet** [comment]
It is accurate and normal because all GPUs that lack a dedicated renderer fall back to the basic framebuffer driver.
