### ISSUE TITLE
Unable to get USB 3.0 controller to work

### ISSUE THREAD

**Issue by mdl054** [foxlet/macOS-Simple-KVM#106]
The controller works during clover but won't load after OSX does. Renesas Technology Corp. uPD720201 USB 3.0 Host Controller. Appears it may not be an issue with this project but with OSX. Any way to load a kext file patch?

**Comment by Pilo11** [comment]
Just use qemu-nbd to mount your ESP image and then place your kext into the CLOVER file structure.

`sudo modprobe nbd max_part=8`
`sudo qemu-nbd --connect=/dev/nbd0 ESP.qcow2`
`sudo mount /dev/nbd0p1 /mnt/`

Now copy your kext to /CLOVER/kexts/other/.

`sudo umount /mnt/`
`sudo qemu-nbd --disconnect /dev/nbd0`

Finished.
Try this kext: [RehabMan is King](https://bitbucket.org/RehabMan/os-x-usb-inject-all/downloads/).
More concrete kext creation with: [this tool](https://github.com/headkaze/Hackintool)

**Comment by mdl054** [comment]
Thank you for the instructions! While that kext didn't work, you helped me learn. Hopefully this can help others too. I have a USB controller that is natively supported now, apparently the Renesas one I had before is a nightmare.

**Comment by tristan-k** [comment]
> Thank you for the instructions! While that kext didn't work, you helped me learn. Hopefully this can help others too. I have a USB controller that is natively supported now, apparently the Renesas one I had before is a nightmare.

Which USB controller can you recommend for a macOS VM?

**Comment by mailinglists35** [comment]
@mdl054 any chance you can tell the supported pcie usb adapter name?
