### ISSUE TITLE
Unable to install Mac OS Catalina

### ISSUE THREAD

**Issue by JKakaofanatiker** [foxlet/macOS-Simple-KVM#109]
When I try to install Mac OS Catalina, it says that it's unable to download. I pinged apple.com and it timed out.
![Mac Error 2](https://user-images.githubusercontent.com/53398711/67394530-a6007400-f5a4-11e9-8181-59a3a8862366.png)
![Mac VM Error](https://user-images.githubusercontent.com/53398711/67394532-a6990a80-f5a4-11e9-819e-5882ccb889e3.png)

**Comment by stepdc** [comment]
same problem here, do not use apfs fix this
