### ISSUE TITLE
Can not install: Disk is locked

### ISSUE THREAD

**Issue by thehalftruth** [foxlet/macOS-Simple-KVM#11]
I can not install it. On the page "Select the disk where you want to install macOS" it says "This disk is locked".

**Comment by Vladimir-pa** [comment]
Get back to main menu , click on disk partition and erase the disk with the 64gb(or w/e u allocated), creating the default partition it suggests.
That should fix the problem.

**Comment by mike-lawrence** [comment]
FYI, I got the "This disk is locked" error too, even after trying to format the drive as either HFS+ or APFS. I eventually quit qemu, deleted the qcow2 file and made one that was bigger (original was set to 20G, recreated one that was 64G) and it worked fine after formatting it as HFS+ (didn't have a chance to try APFS).

**Comment by peterkaosa** [comment]
FYI: also works for sosumi.
