### ISSUE TITLE
Jumpstart.sh doesn't fetch Mac OS High Sierra

### ISSUE THREAD

**Issue by ItzEthan** [foxlet/macOS-Simple-KVM#111]
When using "./jumpstart.sh --high-sierra" the terminal tries to fetch it, then returns the error "Product ID 091-95155 could not be found". Both mojave and catalina work, however I need High Sierra for my graphics card pass through :)

**Comment by foxlet** [comment]
Please try again with the latest git version.

**Comment by wasem1772** [comment]
#131
