### ISSUE TITLE
Safari tabs are full of artifacts

### ISSUE THREAD

**Issue by vladipus** [foxlet/macOS-Simple-KVM#114]
I think this somehow relates to the flickering bug I've reportet earlier. The Safari tabs are hardly usable. Is there a fix to it?
![image](https://user-images.githubusercontent.com/468323/67927473-ba0e2c00-fbc9-11e9-8a4a-3e0ae3b45c93.png)

**Comment by foxlet** [comment]
If you're using software graphics, that's part of the limitations. You need to get an accelerated card to fix some of the issues with macOS.

**Comment by vladipus** [comment]
I see, thank you for the response.
