### ISSUE TITLE
cannot open vfio file

### ISSUE THREAD

**Issue by justindal** [foxlet/macOS-Simple-KVM#12]
get output
```
qemu-system-x86_64: -device vfio-pci,host=00:02.0,bus=port.1,multifunction=on: vfio 0000:00:02.0: failed to open /dev/vfio/1: No such file or directory
```
when trying to launch basic.sh

**Comment by foxlet** [comment]
You need to `sudo insmod vfio-pci` or enable it in your initramfs.

**Comment by juxtind** [comment]
i have if enabled in my initramfs, and when trying to use the insmod command, the module cannot be found. still getting the error

**Comment by masesk** [comment]
Same issue here. I have integrated GPU and Nvidia graphics card. Can't pass through. The `insmod vfio-pci `command outputs 
`insmod: ERROR: could not load module vfio-pci: No such file or directory`

**Comment by zaptrem** [comment]
@justindal How did you solve this issue? The same thing just started happening to me and I'm trying to figure out what caused it.

**Comment by bishoyroufael** [comment]
Any updates regarding this issue ? I am having the same issue while passing my GPU through the vm

**Comment by sk-zk** [comment]
Just run into this issue. In my case, the solution was to remove `-vga qxl \` from `basic.sh`.
