### ISSUE TITLE
Adding an USB device

### ISSUE THREAD

**Issue by carlos-ruiz** [foxlet/macOS-Simple-KVM#128]
Can't to add an USB device, I need to connect a memory usb stick, but can' do it.

I try adding "-device usb-host,hostbus=1,hostaddr=5" to basic.sh file, this because when I run "lsusb" command I'm getting this output
```
carlos@laptop-home:~/osx/macOS-Simple-KVM$ lsusb | grep Kingston
Bus 001 Device 005: ID 13fe:4100 Kingston Technology Company Inc. Flash drive
```
Then the OSX run OK, but when I open Finder I just see this error 
"sb_desc_get_descriptor: 3 unknown type 33 (len 10)"

**Comment by JeremyJStarcher** [comment]
I had success installing a USB flash drive using the vendor and product ID ... then it didn't matter which port I plugged it into.

```
    -usb -device usb-host,productid=0x0043,vendorid=0x2341 \
```

To find those values, plug in a flash drive and then type `dmesg`.  The latest USB device will be listed at the bottom.

**Comment by carlos-ruiz** [comment]
> I had success installing a USB flash drive using the vendor and product ID ... then it didn't matter which port I plugged it into.
> 
> ```
>     -usb -device usb-host,productid=0x0043,vendorid=0x2341 \
> ```
> 
> To find those values, plug in a flash drive and then type `dmesg`. The latest USB device will be listed at the bottom.

Thank you so much, I will try it

**Comment by carlos-ruiz** [comment]
It doesn't work for me, when I run basic.sh script it stucks on this screen

![Screenshot from 2020-02-26 07 47 51](https://user-images.githubusercontent.com/1386434/75350580-63111e80-586c-11ea-9e8b-7f701f44736d.png)

This is the line I added
`-usb -device usb-host,productid=0x6545,vendorid=0x0930 \`

These data was found with dmesg as you suggest
`usb 1-1.1: New USB device found, idVendor=0930, idProduct=6545, bcdDevice= 1.00`

If I remove the line from basic.sh, then VM start OK without the problem I told 

In console I get this messages too, I'm not sure what those mean
![Screenshot from 2020-02-26 07 49 32](https://user-images.githubusercontent.com/1386434/75350777-ad929b00-586c-11ea-99f1-1d1a4f0cba51.png)

Could you see any problem with data I'm adding to basic.sh? 

Thank you so much for helping me.

> I had success installing a USB flash drive using the vendor and product ID ... then it didn't matter which port I plugged it into.
> 
> ```
>     -usb -device usb-host,productid=0x0043,vendorid=0x2341 \
> ```
> 
> To find those values, plug in a flash drive and then type `dmesg`. The latest USB device will be listed at the bottom.

**Comment by felleg** [comment]
+1 on this issue,

**Comment by rameshkumarpby** [comment]
> +1 on this issue. Luckily, I was able to go around it by following these steps:
> 
> 1. Add the line with `-device usb-host,vendorid=....,productid=....`
> 2. Unplug the USB device
> 3. Launch the ./basic.sh script
> 4. Log into the VM
> 5. Connect the USB device

Thank you so much, It works :+1:

**Comment by carlos-ruiz** [comment]
> +1 on this issue. Luckily, I was able to go around it by following these steps:
> 
> 1. Add the line with `-device usb-host,vendorid=....,productid=....`
> 2. Unplug the USB device
> 3. Launch the ./basic.sh script
> 4. Log into the VM
> 5. Connect the USB device

Thank you, It works for me

**Comment by samkelo-nhlapo** [comment]
ive tried it and when i insert the usb it jumps in and out of my main machine which is linux ubuntu but doesnt show anything on the 
![Screenshot from 2021-10-12 14-21-09](https://user-images.githubusercontent.com/72704428/136955132-22fd3552-f967-4ec0-99f0-8f754464b397.png)
VM

**Comment by y0va** [comment]
This works for me with usb storage devices but not with an iPhone.

**Comment by xoofee** [comment]
qume-system-x86_64 should run with sudo. Without sudo qemu cannot make the usb to virtual machine.
