### ISSUE TITLE
Passthrough of internal Intel HD 530 Graphics

### ISSUE THREAD

**Issue by Reeonimus** [foxlet/macOS-Simple-KVM#130]
I have made all the necessary changes to enabble vt-d/iommu/vfio and can confirm my Internal gfx are able to pass-though as I see this when running lspci -k

00:02.0 Display controller: Intel Corporation HD Graphics 530 (rev 06)
        DeviceName:  Onboard IGD
        Subsystem: ASUSTeK Computer Inc. HD Graphics 530
        Kernel driver in use: vfio-pci
        Kernel modules: i915

I have added the below based on your example to the basic.sh but I feel like it may be incorrect?

The VM starts, i get the QEMU window on my host (Manjaro) and can view the clover menu in serial view. The connected display attached to my iGPU is mostly garbled green lines when I boot the base system and I get a kernel panic if I try to boot the already set up OS. Resolution is set to my native monitor display and from what i've found online the HD 530 is compatible. But is there an issue with the below arguments for the passthrough? This is the part I need to research more as i'm not 100% sure exactly what is actually being defined here.

    -vga none \
    -device pcie-root-port,bus=pcie.0,multifunction=on,port=1,chassis=1,id=port.1 \
    -device vfio-pci,host=00:02.0,bus=port.1

**Comment by parkerlreed** [comment]
Did you solve this? A note as to what worked is preferred.

**Comment by Reeonimus** [comment]
I did not solve this but through more research it seems the issues are with the Clover config.plist as MacOS is very picky about graphics implementation. Having learned that I figured this issue is outside the bounds of expecting this project owner to help solve.

**Comment by parkerlreed** [comment]
Ahh ok. Good to know.

**Comment by ipatch** [comment]
doing some research on this topic.

the below may be of interest.

https://wiki.archlinux.org/title/Intel_GVT-g
