### ISSUE TITLE
Possible to run the QEMU window either full screen or maximized?

### ISSUE THREAD

**Issue by dannyvoid** [foxlet/macOS-Simple-KVM#134]
I've got my KVM set up pretty much perfectly, but is there some method of making the window maximized or full-screen when running ./basic.sh? Sorry for the beginner question, first time using this and google wasn't really helping.

**Comment by foxlet** [comment]
Ctrl + Alt + F toggles fullscreen mode.

**Comment by dannyvoid** [comment]
Was worried that was the case. I was hoping for some argument to pass.

**Comment by foxlet** [comment]
If you want it permanently, add it to basic.sh
```
    -full-screen \
```
