### ISSUE TITLE
ModuleNotFoundError: No module named ''click''

### ISSUE THREAD

**Issue by Hostate** [foxlet/macOS-Simple-KVM#14]
On ubuntu18.04, I tried to do
`$ ./jumpstart.sh`
to download OSX, but it said ModuleNotFoundError: No module named 'click'

But I already ran "pip install click" to install module 'click'

**Comment by foxlet** [comment]
You may need to run it as pip3.

**Comment by foxlet** [comment]
You need to install the dependencies: `sudo apt-get install qemu python3 python3-pip`
