### ISSUE TITLE
Sudo (checkera1n) password

### ISSUE THREAD

**Issue by Moltivie** [foxlet/macOS-Simple-KVM#145]
Hey there,
Basically I have my VM working on Qemu. The fact is that once inside the VM, when I have to make some actions, it asks my the password for `checkera1n` user. I have tried typing an empty password and `checkera1n` also but they are incorrect. Does someone knows it?

Thanks.

**Comment by deadair3210** [comment]
Nothing involving the kvm would have anything to do with a guest is user

**Comment by Moltivie** [comment]
That was helpful :)

**Comment by deadair3210** [comment]
You are submitting an issue against something that is completely different from your issue, what do you honestly expect?

**Comment by foxlet** [comment]
When setting up macOS, you had to specify the password for a new user. If you're using third-party images, I can't help with that.
