### ISSUE TITLE
Could not open 'BaseSystem.img': No such file or directory

### ISSUE THREAD

**Issue by jetaimefrc** [foxlet/macOS-Simple-KVM#146]
When i executed ./basic.sh
I got this error:
```
qemu-system-x86_64: -drive id=InstallMedia,format=raw,if=none,file=BaseSystem.img:
Could not open 'BaseSystem.img': No such file or directory
```
Hope you help me! Thank!

**Comment by foxlet** [comment]
Run `jumpstart.sh` as noted in the instructions (if you already didn't). If you already installed macOS, remove the line from `basic.sh`.
