### ISSUE TITLE
Snow leopard, for Rosetta ?

### ISSUE THREAD

**Issue by stuaxo** [foxlet/macOS-Simple-KVM#148]
Would it be possible to add Snow Leopard ?

While there are many older versions of OSX, Snow Leopard is the last version to run PPC apps with Rosetta.

**Comment by foxlet** [comment]
Snow Leopard was never distributed over the internet, but if you have a disc, you can still install it.

**Comment by stuaxo** [comment]
Cheers :)

**Comment by KDGNOR** [comment]
@stuaxo did get Snow Leopard to work ?

**Comment by stuaxo** [comment]
I didn't get round to trying this in the end.
