### ISSUE TITLE
unable to find any master var store for loader

### ISSUE THREAD

**Issue by Hostate** [foxlet/macOS-Simple-KVM#15]
I can run hackintosh with ./basic.sh. But in virt-manager I can't run it. Get output:

Error starting domain: operation failed: unable to find any master var store for loader: ~/hackintosh/macOS-Simple-KVM/firmware/OVMF_CODE.fd

**Comment by foxlet** [comment]
`git checkout -- firmware/OVMF_VARS-1024x768.fd` or restore the OVMF_VARS file.

**Comment by Sepehr13** [comment]
this problem still exist for some reason.

![image](https://user-images.githubusercontent.com/21054209/109382211-58142280-78f4-11eb-9b4c-a90d9028ac4a.png)


And here's my OSX.xml

![image](https://user-images.githubusercontent.com/21054209/109382180-2307d000-78f4-11eb-93b1-2df273bf0c57.png)

**Comment by iamchriswick** [comment]
@Sepehr13 git checkout -- firmware/OVMF_VARS-1024x768.fd

**Comment by CrazyVibes07** [comment]
> @Sepehr13 git checkout -- firmware/OVMF_VARS-1024x768.fd

Still doesnt work, I have all the files.
