### ISSUE TITLE
How the ESP is created

### ISSUE THREAD

**Issue by nift4** [foxlet/macOS-Simple-KVM#151]
I'm wondering, this script does transparently download macOS and launch QEMU but the ESP.qcow2 can't be generated by the user AFAIK. (But this is my first try with Hackintosh). How did you created it @foxlet?

**Comment by Pilo11** [comment]
Good question. Very interesting for us :D

**Comment by DragonSWDev** [comment]
It seems it's included in repository so you download it with rest of scripts with git. This ESP partition image has configured Clover bootloader which is used to boot macOS on nonApple hardware. Boot scripts is set to boot from this image so that's why it's working.

**Comment by confiks** [comment]
@foxlet Would you have any basic pointers on how `ESP.qcow2` is built?

**Comment by foxlet** [comment]
Some basic pointers, it's just a blank FAT32 partition with the ESP flag set, and files extracted from the ISO version of Clover (to avoid the Apple Installer requirements). `startup.nsh` is also copied to get around the lack of NVRAM variables when a new machine is created.

**Comment by nift4** [comment]
Thanks for the info 🙂

**Comment by otuva** [comment]
Here's `tree` output of ESP.qcow2

```
.
├── EFI
│   ├── BOOT
│   │   └── BOOTX64.efi
│   └── CLOVER
│       ├── CLOVERX64.efi
│       ├── config.plist
│       ├── drivers64UEFI
│       │   ├── ApfsDriverLoader-64.efi
│       │   ├── apfs.efi
│       │   ├── AppleImageCodec-64.efi
│       │   ├── AppleKeyAggregator-64.efi
│       │   ├── AppleKeyFeeder-64.efi
│       │   ├── AppleUITheme-64.efi
│       │   ├── AptioMemoryFix.efi
│       │   ├── DataHubDxe-64.efi
│       │   ├── FirmwareVolume-64.efi
│       │   ├── FSInject-64.efi
│       │   ├── SMCHelper-64.efi
│       │   └── VBoxHfs-64.efi
│       ├── kexts
│       │   ├── 10.13
│       │   ├── 10.14
│       │   │   └── VoodooHDA.kext
│       │   │       └── Contents
│       │   │           ├── _CodeSignature
│       │   │           │   └── CodeResources
│       │   │           ├── Info.plist
│       │   │           └── MacOS
│       │   │               └── VoodooHDA
│       │   ├── 10.15
│       │   └── Other
│       │       └── VoodooHDA.kext
│       │           └── Contents
│       │               ├── _CodeSignature
│       │               │   └── CodeResources
│       │               ├── Info.plist
│       │               └── MacOS
│       │                   └── VoodooHDA
│       └── tools
│           ├── bdmesg.efi
│           ├── Shell32.efi
│           ├── Shell64.efi
│           ├── Shell64U.efi
│           └── Shell.inf
├── nvram.plist
└── startup.nsh
```

[ESP.qcow2.zip](https://github.com/foxlet/macOS-Simple-KVM/files/11361685/ESP.qcow2.zip)
