### ISSUE TITLE
Disk Utilitys not showing newly created drive

### ISSUE THREAD

**Issue by SuperSlimey5** [foxlet/macOS-Simple-KVM#155]
I created the drive as I'm supposed to and I add the 2 lines of code after typing 'sudo bash basic.sh'
But when I enter Disk Utility's it doesn't show the drive, and thus i can't erase it for my MacOS install.

**Comment by SuperSlimey5** [comment]
I figured it out

**Comment by Ewilso** [comment]
How did you fix this issue? I've been having it too.

**Comment by SuperSlimey5** [comment]
I don’t remember sorry



On 29 Jun 2020, at 1:40 am, wilson <notifications@github.com<mailto:notifications@github.com>> wrote:


How did you fix this issue? I've been having it too.
