### ISSUE TITLE
Set default boot disk?

### ISSUE THREAD

**Issue by rangaritad** [foxlet/macOS-Simple-KVM#158]
Hi,

 Is it possible to set a default boot disk? in order to avoid the manual step of selecting the boot disk each time the VM restarts if so, how can I do it? (I've found some information in Clover related forums but none of them work for me.

 Regards,

**Comment by XiovV** [comment]
@rangaritad you have an option to select a boot disk? I have to reinstall every time I boot the VM.

**Comment by rangaritad** [comment]
Yes @XiovV,  I can see the disk where I installed the OS among other options (reinstall option, clover settings, etc)

**Comment by rangaritad** [comment]
I just found the answer: 
 At Clover's boot manager:
1. Click on "Start UEFI Shell 64"
2. SHELL> edit fs0:\EFI\CLOVER\config.plist
3.  Locate the section Boot -> Arguments -> DefaultVolume -> string and replace the value by the volume disk name (in my case it was created as osx)
4. Save (it's a kind of nano editor) and quit
5. SHELL> exit
6. Reboot

**Comment by vanlooverenkoen** [comment]
Works like a charm. The volume will be set as default startup volume. a countdown will be set of 5 seconds so you can always stop the clover countdown and stay in the clover boot menu
