### ISSUE TITLE
Proxmox

### ISSUE THREAD

**Issue by ameeno** [foxlet/macOS-Simple-KVM#161]
Hello, can you give me a config file for proxmox that will boot this project?

I can use clonezilla boot to mirror the hard drives/efi, but do not know how exactly the qemu xml code maps to proxmox conf files.

some stuff is missing??

**Comment by ameeno** [comment]
Ok i got a good proxmox config going.

**Comment by badstorm** [comment]
Can you post the conf?

**Comment by ameeno** [comment]
Sure, Basically I pushed the Clover image to the proxmox with ISO extension and mounted/installed 

I have also modified my ovmf on proxmox using this guide: https://gitlab.com/pve-edk2-firmware-clover/pve-edk2-firmware-clover

args: -drive 'if=pflash,unit=0,format=raw,readonly,file=/usr/share/pve-edk2-firmware-clover//OVMF_CODE.fd' -drive 'if=pflash,unit=1,format=raw,id=drive-efidisk0,file=/usr/share/pve-edk2-firmware-clover//OVMF_VARS.fd' -smbios type=2 -machine type=q35,kernel_irqchip=on -device isa-applesmc,osk="ourhardworkbythesewordsguardedpleasedontsteal(c)AppleComputerInc" -device usb-kbd -device usb-tablet -cpu Penryn,kvm=on,vendor=GenuineIntel,+invtsc,vmware-cpuid-freq=on,+pcid,+ssse3,+sse4.2,+popcnt,+avx,+aes,+xsave,+xsaveopt,check
balloon: 0
boot: cdn
bootdisk: sata0
cores: 2
cpu: host
localtime: 1
machine: q35
memory: 3072
name: macOS-Catalina
net0: e1000-82545em=XXX,bridge=vmbr0
numa: 0
ostype: other
sata0: local-zfs:vm-103-disk-0,backup=0,discard=on,size=64G
smbios1: uuid=cbcf9d9a-c152-411c-8911-349969148059
sockets: 1
tablet: 0
vga: qxl



XXX= redacted.
