### ISSUE TITLE
click module in python2.7 and python 3.7

### ISSUE THREAD

**Issue by zischknall** [foxlet/macOS-Simple-KVM#17]
I am running Ubuntu 19.04 and have the requirements `qemu python3 python3-pip` including the python3.7 version of everything installed and when i try to run `./jumpstart -m` I get this error:

`DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Requirement already satisfied: requests in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 1)) (2.21.0)
Requirement already satisfied: click in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 2)) (7.0)
Traceback (most recent call last):
  File "fetch-macos.py", line 9, in <module>
    import click
ModuleNotFoundError: No module named 'click'`

**Comment by PR1YANKPAT3L** [comment]
I was facing the exact issue few minutes ago, I managed to fix it by installing python3-pip and installing click module:
`sudo apt install python3-pip && pip3 install click`

**Comment by zischknall** [comment]
It says everything would be already installed an links me to a python2.7 version of click even though i specified pip3.
```
$ sudo apt install python3-pip && pip3 install click
Reading package lists... Done

Building dependency tree       

Reading state information... Done

python3-pip is already the newest version (18.1-5).

0 upgraded, 0 newly installed, 0 to remove and 5 not upgraded.

DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.

Requirement already satisfied: click in /usr/local/lib/python2.7/dist-packages (7.0)
```

**Comment by michael-gracy** [comment]
Check the shell declaration at the top of the jumpstart script. If is says something like '/usr/bin/python' make sure that resolves to python3. If it is using 'env', same requirement applies.

**Comment by zischknall** [comment]
Well jumpstart is a shell script and the python version used is defined in tools/FetchMacOS/fetch.sh which starts fetch-macos.py with the set python binary. And even when i want to explicitly tell the  fetch-macos.py to use python3 with `#!/usr/bin/python3` it errors out.

**Comment by zischknall** [comment]
Okay, i got it running by installing the python3-click package from the repositories. But still no clue why pip3 was refusing to install the click package for python3 just because the package for python2.7 was installed.
