### ISSUE TITLE
Only have 2GB in macOS

### ISSUE THREAD

**Issue by zswierz** [foxlet/macOS-Simple-KVM#183]
I would create a 40GB drive, and then in the Install it shows up as QEMU HARDDISK MEDIA. I format it for macOS and continue. I then install the macOS on that formatted drive. Then, the drive shows up macOS Base System (2GB) how do I get my macOS to use my 40GB drive?

**Comment by jjjdor** [comment]
I have the same issue

**Comment by jjjdor** [comment]
Solved it, you will find your 40gb drive in the disk utility, you then just need to erase the drive and set it to GUID partition scheme. (The drive not a volume !)
