### ISSUE TITLE
It fetches Catalina instead of High Sierra

### ISSUE THREAD

**Issue by gabrieldeholanda** [foxlet/macOS-Simple-KVM#189]
When I run ./jumpstart.sh --high--sierra and after run ./basic.sh it appears to install catalina.
How I am supposed to proceded to fix this?

**Comment by kev-sharp** [comment]
you have to run 'jumpstart.sh --high-sierra'!!!

**Comment by gabrieldeholanda** [comment]
I just realized about it
thank youu so much!
