### ISSUE TITLE
iPadOS 13 w/ sidecar limited by iMac 2009 - give option to set this and resolution of VM

### ISSUE THREAD

**Issue by bmw417** [foxlet/macOS-Simple-KVM#19]
Hi, 

I have the newest iPad Pro 12.9" that should have sidecar support with the following list of newer Mac models:

Late 2015 27" iMac or newer
2017 iMac Pro
Mid 2016 MacBook Pro or newer
Late 2018 Mac mini or newer
Late 2018 MacBook Air or newer
Early 2016 MacBook or newer
2019 Mac Pro

Taken from https://www.macrumors.com/2019/06/06/macos-catalina-sidecar-limited-to-newer-macs

There is a few terminal hack workarounds that seem to work on baremetal Macs, but I've tried entering the same commands with no luck. I also have my Catalina VM on a bridged network with my iPad on the same 192.168.0.* domain, so there shouldn't be any NAT issues. It seems as though the settings for setting the iMac model number and VM resolution are set in one of the .fd binary files from the firmware directory, but I can't modify those easily. I've also attempted to run hexdump -C on both files and grep for the resolution and iMac ASCII string with no luck.

**Comment by foxlet** [comment]
That's in the ESP, `\EFI\CLOVER\config.plist`.
