### ISSUE TITLE
In mac os it appears the translucent effect is disabled. (Small Issue, nothing to be concerned of)

### ISSUE THREAD

**Issue by YUZI22** [foxlet/macOS-Simple-KVM#195]
On for example a macbook the translucent effect will be enabled on docks and windows, but on this it is disabled even though "reduce transparency" is unchecked. It may not be relevant to this specific git repo, but I think it's disabled on a kernel level. Any way to enable it again, I keep thinking that maybe clover boot args are disabling it somehow. It's a pretty small issue but.
![Screenshot 2020-04-27 at 22 31 46](https://user-images.githubusercontent.com/42190308/80422909-e7b50300-88d6-11ea-8c0f-bb8e5841cb48.png)
Vs a macbook for example:
![maxresdefault](https://user-images.githubusercontent.com/42190308/80422977-0915ef00-88d7-11ea-955d-e85a92d174b6.jpg)

**Comment by UnicornsOnLSD** [comment]
This is because QEMU (specifically QXL) can't do full video acceleration. To fix this, you need to give QEMU a real GPU, which you can learn how to do here: https://github.com/foxlet/macOS-Simple-KVM/blob/master/docs/guide-passthrough.md

Note that you need two graphics cards to do this.

**Comment by YUZI22** [comment]
Ah i see, thank you.
