### ISSUE TITLE
Unable to install OS X 10.7. 

### ISSUE THREAD

**Issue by rdtor** [foxlet/macOS-Simple-KVM#20]
Hi i am trying to run ./jumpstart.sh --lion.
It downloads the dmg file but when i run ./basic.sh the version is 10.15 beta

**Comment by AwlsomeAlex** [comment]
I don't believe @foxlet supports Lion, as the jumpstart tool only works with High Sierra, Mojave and Catalina.

**Comment by foxlet** [comment]
You will need to provide your own installation media (BaseSystem) from the App Store as Lion wasn't a free product at the time.
