### ISSUE TITLE
23 hours estimated installation time

### ISSUE THREAD

**Issue by krmkcbs** [foxlet/macOS-Simple-KVM#204]
i installed it correctly on Elementary os 5.1 and macos installation gives me 23 hours estimate.Is there a way to fix this?

**Comment by apiraino** [comment]
Related to #187 and #157. The installation download gigabytes of packages, so first thing I'd ensure to have a solid and fast connection.

Once the installation is complete, this is not an issue anymore (as far as I can see)

**Comment by krmkcbs** [comment]
it is stuck on 2 minutes left

**Comment by gazhay** [comment]
I've got a working, stable, fast fibre connection and its 29 hours 31 minutes and has been for an hour.
