### ISSUE TITLE
How to share files with host

### ISSUE THREAD

**Issue by demolere** [foxlet/macOS-Simple-KVM#21]
I tried to follow [this article](https://xapax.github.io/blog/2017/05/09/sharing-files-kvm.html) in order to share files with the host os with no success.  User "libvirt-qemu" does not exist.

**Comment by foxlet** [comment]
That type of file sharing won't work with macOS, you will need to use tun/tap networking and a networked filesharing protocol like Samba, SSH, or FTP.

**Comment by demolere** [comment]
Thank you for the idea. I am using an FTP for now.

**Comment by KesleyDavid** [comment]
> Thank you for the idea. I am using an FTP for now.

as you did?
