### ISSUE TITLE
adding a physical partation to the vm 

### ISSUE THREAD

**Issue by alansarkar** [foxlet/macOS-Simple-KVM#218]
I have ovfm enabled and gpu passthrough is working great  but for somereason the vm or mac cant detect  physical partation passthrough . I tried using as  -device or as usb and also simple -hdb but for all of them the vm did boot in but mac couldn't find any new partation.

**Comment by foxlet** [comment]
You can add a physical device by passing it as a disk, make sure the hard disk and all its partitions are unmounted, however.

    -drive id=PhysicalDisk,if=none,file=/dev/sdb \
    -device ide-hd,bus=sata.5,drive=PhysicalDisk \
