### ISSUE TITLE
Losing input device randomly

### ISSUE THREAD

**Issue by demolere** [foxlet/macOS-Simple-KVM#22]
I am using the keyboard and trackpad on my laptop, and experiencing random input device freezes that don't go away unless I turn off the VM.

The mouse cursor and keyboard would suddenly not respond anymore. The guest OS seems to be running normally, expect that now I don't have no control over it, other than being able to monitor the screen. I can still escape mouse and keyboard with `ctrl-alt` to the host OS, but recapturing them in the guest OS also doesn't solve this issue.

CPU: i5-7200U
Guest: Mojave
Host: Ubuntu Mate 18.04.2

All default settings in the `basic.sh` script.

Would be glad to provide logs, but I'm very new to QEMU/KVM, and not sure which log is needed.

**Comment by foxlet** [comment]
Check that display sleep isn't enabled in Energy Saver.

**Comment by mcornella** [comment]
Can confirm the solution, after I disabled all energy saving settings the problem hasn't happened again.

**Comment by demolere** [comment]
Thanks, will try this out later and close the issue if it also fixes the problem for me.
