### ISSUE TITLE
[Feature request] More verbose virt-manager instructions

### ISSUE THREAD

**Issue by treymerkley** [foxlet/macOS-Simple-KVM#229]
I'm having trouble adding MyDisk.qcow2 to the virt-manager launcher. Can you explain the specific steps to add it to the machine?

**Comment by ProximaB** [comment]
In case to install system you need to create and mount a hard disk.
`qemu-img create -f qcow2 yourdisk.qcow2 64G`

After that add to startup script these two lines:
` -drive id=someId,if=none,file=createdDisk.qcow2 \ #< - setup a virtual hard drive`    
`-device ide-hd,bus=sata.4,drive=someId \ # <- will assign a bus to the device`

**Comment by poisonimy** [comment]
You have to open the VM in virt-manager, go to View > Details, and then click Add Hardware. Select Storage from there, and add MyDisk.qcow2.

**Comment by treymerkley** [comment]
Huh, that was infuriatingly simple, thanks. It's still not working, something to do with my network, but I figured out something that works anyhow. Do you know of a way to set the default zoom?

**Comment by littalthiefu** [comment]
The default zoom? If you mean scaling, I think the options are in View > Scale display. If you didn't mean scaling, then idk.
