### ISSUE TITLE
Catalina 10.15.5 won't boot without disabling InjectATI in the boot menu

### ISSUE THREAD

**Issue by sandercox** [foxlet/macOS-Simple-KVM#236]
Having issues with booting the catalina image since 10.15.5 (on .4 it was working without issues).

Using a AMD Radeon RX5700xt for graphics and it crashes at startup unless when I disable "InjectATI" in the clover options.

However I have no clue on what to add to the config.plist to make these settings stick - so I don't have to manually deselect it every time it boots.

**Comment by ciokan** [comment]
Somewhat offtopic. I wasted days on this issue and I still cannot pass-through a RX5700xt. Did you do anything in particular not found on this repo/guide/docs?

**Comment by sandercox** [comment]
@ciokan what I did was add a ROM file for the card (in my case a PowerColor RedDevil). Now I do not get the clover menu on the GPU output but i still have that in my virt-manager console (using serial port). I think I also had to remove the Graphics (SPICE) and VGA parts from my config.

As said I need to use the menu to disable the InjectATI (Clover boot options, graphics) every boot since the machine updated to 10.15.5. 

```
    <hostdev mode='subsystem' type='pci' managed='yes'>
      <source>
        <address domain='0x0000' bus='0x23' slot='0x00' function='0x0'/>
      </source>
      <rom file='/home/sander/Powercolor.RX5700XT.8176.190808.rom'/>
      <address type='pci' domain='0x0000' bus='0x02' slot='0x00' function='0x0'/>
    </hostdev>
```

Romfiles can be found on [TechPowerup](https://www.techpowerup.com/vgabios/?manufacturer=AMD&model=RX+5700+XT)

**Comment by ciokan** [comment]
Thanks. Managed to get it working. Oddly enough, I have to disable `injectATI` for it to work.

**Comment by sandercox** [comment]
Glad it also worked for you!

Did you manage to have get InjectATI to be unmarked automatically during boot?

**Comment by ciokan** [comment]
Nope. I have to uncheck that thing each time I boot otherwise the system
blocks after the loading bar (black screen)

**Comment by sandercox** [comment]
Ok finally found a fix for that issue as well.

```bash
sudo mkdir /Volumes/EFI
sudo mount -t msdos /dev/disk0s1 /Volumes/EFI
## edit /Volumes/EFI/EFI/CLOVER/config.plist
diskutil unmount /Volumes/EFI
```
Then the next boot it won't check the InjectATI.

Make sure the `config.plist` contains:
```
	<key>Graphics</key>
	<dict>
		<key>Inject</key>
		<dict>
			<key>ATI</key>
			<false/>
		</dict>
	</dict>
```
