### ISSUE TITLE
sound cracking with osX 11.3 on linux.

### ISSUE THREAD

**Issue by rdtor** [foxlet/macOS-Simple-KVM#24]
hi, I am trying to use the default soundvoodo hda with default build.sh, howeve the sound is playing and stopping without any continuity.

**Comment by kyleharte** [comment]
Agree with this issue although i was booting Mojave on Ubuntu 19.04 and the sound of my music playing progressively became more crackily

**Comment by foxlet** [comment]
You will want to look into PulseAudio optimizations as some distros do not ship sane defaults.

**Comment by rdtor** [comment]
yes i think it was the host OS, i tried in another fresh install and sound works fine however it get muted if its not connected to internet
