### ISSUE TITLE
More vram 

### ISSUE THREAD

**Issue by xyanlucasx** [foxlet/macOS-Simple-KVM#241]
I'm new to this. Is there really no way to allocate more video memory? I have a ryzen and GPU Passthrought is not an alternative for me, as I only have one GPU (gtx 960 4gb).

I don't care about the MAC version, I just wanted to experiment with a pleasant experience, any configuration that gives me more video will be welcome.

I am currently running Catalina in 1080p with 7mb of video.

**Comment by ashwinkey04** [comment]
I have only 3mb VRAM. I am not able to use the VGA driver as well

**Comment by foxlet** [comment]
No, the system without a dedicated GPU will only use up enough memory to draw the screen of your particular resolution.

You can however try the `-vga std` driver in `basic.sh` and see if that's any faster.

**Comment by ashwinkey04** [comment]
Is it possible to make a passthrough of my laptop's GPU? (Intel UHD 620)

**Comment by LJLee37** [comment]
You can, but if you have intel graphics ONLY, you shouldn’t. Otherwise the host OS will not boot properly.

**Comment by foxlet** [comment]
It's possible but the requirements to enable it (shared memory) is out of the project scope.

**Comment by kriptonian1** [comment]
> No, the system without a dedicated GPU will only use up enough memory to draw the screen of your particular resolution.
> 
> You can however try the `-vga std` driver in `basic.sh` and see if that's any faster.

in which line should i put this `-vga std`
