### ISSUE TITLE
"The recovery server could not be contacted"

### ISSUE THREAD

**Issue by smorpaket** [foxlet/macOS-Simple-KVM#242]
![The recovery server could not be contacted](https://user-images.githubusercontent.com/17946529/83966828-e9ea8400-a8bc-11ea-83d2-37609cd6e6c6.png)

**Comment by tonebender** [comment]
I ran into this too but have not found a solution.
Changing NIC device to "vmxnet3" in basic.sh as per https://forums.unraid.net/topic/91749-unable-to-contact-recovery-server-from-vm did not help.

**Comment by micaelillos** [comment]
Had the same problem,  what worked for me was to use a wired connection on a different network.

**Comment by MCOfficer** [comment]
Did i miss something? why was this closed?

**Comment by smorpaket** [comment]
> Did i miss something? why was this closed?

I don't know, since the problem still persists on some Ubuntu machines. Weirdly enough works on POP!_OS

**Comment by foxlet** [comment]
Internet connectivity changes between locations and there's no control this project has over that. If it's an OS issue, I'll leave it open.

**Comment by MCOfficer** [comment]
I can't be sure, but i recall checking the internet from *inside* the VM by doing pings and traceroutes, so i'd guess this is not a problem with the VM configuration.

**Comment by smorpaket** [comment]
> I can't be sure, but i recall checking the internet from *inside* the VM by doing pings and traceroutes, so i'd guess this is not a problem with the VM configuration.

Did the same thing. So the DNS did not seem to be the problem. I also had better success when doing it from a linksys router's Ethernet compared to Asus'.

**Comment by leohanyan** [comment]
I had the same issue. It was a network problem.
I'm using archlinux and not sure why systemd-networkd not working with VM, but when I switched from systemd-networkd to dhcpcd (of course with wired connection) it worked as intended!
You can check if you are connected with macos's terminal by pinging when installer launched.
Note. Restart the computer after enabling dhcpcd.service

**Comment by MCOfficer** [comment]
Ok, perhaps i wasn't clear enough. Internet was working from inside the VM (indicated by traceroutes and pings), but i still got the error mentioned in this issue.

**Comment by IMEVER** [comment]
Same issue, I can browser web using safari, but cannot contact recovery server!
Solved just after reboot

**Comment by aptgetgit** [comment]
Faced the same issue, installing with changed mac address in basic.sh worked for me.
Used the mac generated with `openssl rand -hex 6 | sed 's/\(..\)/\1:/g; s/:$//'` on the very first run of `basic.sh` and everything worked fine.
Maybe the default mac in basic.sh is used a lot that's why the server refuses to connect.
