### ISSUE TITLE
ModuleNotFoundError: No module named 'click'

### ISSUE THREAD

**Issue by dooman17** [foxlet/macOS-Simple-KVM#246]
Despite having click installed, it keeps giving me this error when running jumpstart.sh

`Requirement already satisfied: requests in /home/doom/.local/lib/python2.7/site-packages (from -r requirements.txt (line 1)) (2.23.0)
Requirement already satisfied: click in /home/doom/.local/lib/python2.7/site-packages (from -r requirements.txt (line 2)) (7.1.2)
Requirement already satisfied: certifi>=2017.4.17 in /home/doom/.local/lib/python2.7/site-packages (from requests->-r requirements.txt (line 1)) (2020.4.5.2)
Requirement already satisfied: chardet<4,>=3.0.2 in /home/doom/.local/lib/python2.7/site-packages (from requests->-r requirements.txt (line 1)) (3.0.4)
Requirement already satisfied: idna<3,>=2.5 in /home/doom/.local/lib/python2.7/site-packages (from requests->-r requirements.txt (line 1)) (2.9)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /home/doom/.local/lib/python2.7/site-packages (from requests->-r requirements.txt (line 1)) (1.25.9)
Traceback (most recent call last):
  File "fetch-macos.py", line 9, in <module>
    import click
ModuleNotFoundError: No module named 'click'
`

**Comment by foxlet** [comment]
Check if you have a different version of python being called.

**Comment by dooman17** [comment]
Yup, that was it iirc. Needed python 3. Installed it and it worked
