### ISSUE TITLE
No accelerator found

### ISSUE THREAD

**Issue by deremuTVCode** [foxlet/macOS-Simple-KVM#248]
I get this error when executing basic.sh:
> qemu-system-x86_64: -machine accel=kvm: No accelerator found

**Comment by Marfjeh** [comment]
What CPU do you have? This error will pop up if your CPU does not support virtualization. Or it is disables in your bios.

To enable it, look into your bios.

**Comment by deremuTVCode** [comment]
Its on a arm CPU 😄.

**Comment by Marfjeh** [comment]
There is your problem.
