### ISSUE TITLE
jumpstart.sh permission denied

### ISSUE THREAD

**Issue by yoni1857** [foxlet/macOS-Simple-KVM#262]
When I try to run jumpstart.sh I get the error "bash: ./jumpstart.sh: Permission denied"

I've tried using chmod to make the file executable but it didn't fix the problem

**Comment by SuperKaninchen** [comment]
What was the exact command that you used to make it executable?

**Comment by yoni1857** [comment]
I used ./jumpstart.sh

**Comment by SuperKaninchen** [comment]
I mean the chmod command including the used arguments

**Comment by yoni1857** [comment]
I think it might be some internal issue because I copied it to another folder and it seems to work now. I've used chmod +x. I'm gonna close the issue now sorry for wasting your time.

**Comment by SuperKaninchen** [comment]
No worries! At least it works now. Feel free to open another issue if you run into any other problems!
