### ISSUE TITLE
wifi conectivity

### ISSUE THREAD

**Issue by narenkpai** [foxlet/macOS-Simple-KVM#271]
when I try to use the macos installer, It takes up all my WiFi connectivity in my house and it it says it will take 3 hours to do. (it is sort of old so I don't want to leave it running at night)

**Comment by putra1990** [comment]
try lan conecction

**Comment by putra1990** [comment]
iam done

**Comment by narenkpai** [comment]
My computer does not have wifi, It only has ethernet, so that is what I have been doing the whole time. Could that be the problem?

**Comment by foxlet** [comment]
You will need some type of internet connection to complete the installation. You can create a flash drive on an existing Mac to do it offline.

**Comment by narenkpai** [comment]
I use Ethernet, or do I have to use WiFi

**Comment by narenkpai** [comment]
I think that this may be a problem with my PC. If I have a solution for this, I will let you know, sorry if I wasted your time. Thanks
