### ISSUE TITLE
Fresh install giving errors, 0xE @ AAPL,CoProcessorReboot

### ISSUE THREAD

**Issue by bitfabrikken** [foxlet/macOS-Simple-KVM#283]
Been running macOS-Simple-KVM for about a year with no issues (thanks!).
Updated Debian today and now I can't boot anything. 
I tried cloning the macOS-Simple-KVM repo and starting over, but still getting the error on boot.
Maybe the cause is that the qemu packages were updated from 1:5.0-5 to 1:5.0-6.

Operating System: Debian GNU/Linux bullseye/sid
Kernel: Linux 5.7.0-1-amd64

Here's the error message (couldn't find the log file):

![image](https://user-images.githubusercontent.com/2039652/87913773-e62b4f00-ca6f-11ea-90bc-1551c82365e8.png)

**Comment by BlueSlimee** [comment]
Have you tried deleting the pre-linked kernel and building it again? This guide shows you how: https://www.insanelymac.com/forum/topic/327815-how-to-fix-%E2%80%9Cerror-loading-kernel-cache-0x1%E2%80%9D-on-existing-1013-installations/

**Comment by bitfabrikken** [comment]
@BlueSlimee thanks for replying - I haven't tried that yet, but isn't that only if I experience problems with a specific HDD image? If I boot the install image, it just hangs on "AMF: Only 247/256 slide values are usable! Valid slides: 9-255" and reboots after ½-1 hours.

**Comment by mruss77** [comment]
@bitfabrikken I have the exact same issue and symptoms. I don't think I can rebuild the pre-linked kernel since I can't boot to recovery.

I am also on Debian bullseye, same kernel and qemu version.

**Comment by bitfabrikken** [comment]
@mruss77 glad to hear I'm not alone. Have you tried downgrading qemu and the other qemu apt packages? I haven't had time yet, couldn't figure it out really, but it's worth trying.

**Comment by mruss77** [comment]
I tried uninstalling qemu and running "apt install qemu-kvm=1:5.0-5" but I get:

     E: Version '1:5.0-5' for 'qemu-kvm' was not found

It seems like the old version is no longer in the testing repositories. I'm wondering if I can install it via snap.... or worst case, maybe Docker. In the meantime I booted from an Ubuntu live USB disk and was able to run my VM and extract my data from it.

**Comment by bitfabrikken** [comment]
@mruss77 Got it working! 
Found an issue for it here: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=964247
I installed the latest version of qemu packages from unstable - 1:5.0-13
And now it works :)

```
apt -t unstable install qemu qemu-system-arm qemu-system-data qemu-system-mips qemu-system-ppc qemu-system-sparc qemu-system qemu-utils qemu-system-gui qemu-x86-64
```
