### ISSUE TITLE
install to another disk / partition

### ISSUE THREAD

**Issue by PublicNFT** [foxlet/macOS-Simple-KVM#292]
Hello people,
I currently use Manjaro Linux with a 100GB SSD primary disk, I only have 20GB of free space.
However I have a secondary disk of 1TB I would like to know how I do so that my installation is on the secondary disk!
Is there such a possibility since the total installation of OX is over 60GB?

**Comment by amaralbc** [comment]
Also, is it possible to install it in the hard drive itself rather than in an emulated disk? I imagine performance would be much better

**Comment by CubeBank** [comment]
I tried to create a symbolic link, pointing the directory / snap / sosumi to / run / media / droid / DataGlobal / macox but it doesn't work, so I tried to move the susomi directory to direct / run / media / droid / DataGlobal / macox and neither did it worked.
If anyone has a solution I would appreciate it. I only have 20GB on /
and I would love to have osX running virtualized on my segudon disk! tks

**Comment by PublicNFT** [comment]
Yes it is possible, I just added the full path to the album, everything is going well so far!
qemu-img create -f qcow2 /run/media/droid/DataGlobal/macox/Disco-osX.qcow2 70G    
       
Formatting '/run/media/droid/DataGlobal/macox/Disco-osX.qcow2', fmt=qcow2 size=75161927680 cluster_size=65536 lazy_refcounts=off refcount_bits=16
[android macox]# ls -lhat
total 208K
-rw-r--r-- 1 root root 194K ago  6 06:50 Disco-osX.qcow2
drwxr-xr-x 3 root root 4,0K ago  6 06:50 .
drwxr-xr-x 7 root root 4,0K ago  6 06:48 macOS-Simple-KVM
drwxr-xr-x 9 root root 4,0K ago  6 05:18 ..

**Comment by bvmy** [comment]
> Yes it is possible, I just added the full path to the album, everything is going well so far!
> qemu-img create -f qcow2 /run/media/droid/DataGlobal/macox/Disco-osX.qcow2 70G
> 
> Formatting '/run/media/droid/DataGlobal/macox/Disco-osX.qcow2', fmt=qcow2 size=75161927680 cluster_size=65536 lazy_refcounts=off refcount_bits=16
> [android macox]# ls -lhat
> total 208K
> -rw-r--r-- 1 root root 194K ago 6 06:50 Disco-osX.qcow2
> drwxr-xr-x 3 root root 4,0K ago 6 06:50 .
> drwxr-xr-x 7 root root 4,0K ago 6 06:48 macOS-Simple-KVM
> drwxr-xr-x 9 root root 4,0K ago 6 05:18 ..

@CubeBank how to add  the full path to the album, where is the album? Thanks
