### ISSUE TITLE
PCIe USB host passthrough but keyboard mouse not working

### ISSUE THREAD

**Issue by mogupta** [foxlet/macOS-Simple-KVM#294]
Hi, Excellent works guys
One small problem. I am able to passthrough the entire USB PCIe controller. IPhone , external USB storage all works except mouse and keyboard. Is their anything I can do to fix it. 
I am using Catalina as guest and Ubuntu 20 as Host. 
The host keyboard mouse works but is laggy

**Comment by mogupta** [comment]
![image](https://user-images.githubusercontent.com/479667/89725117-9e259980-da29-11ea-97c9-1adec7b2baee.png)

**Comment by ghost** [comment]
Are you using USB 3.0 on KVM?

**Comment by mogupta** [comment]
I am not sure how to make it USB 3 or USB2 . I just added the PCIe device via virt manager

![image](https://user-images.githubusercontent.com/479667/89745668-0086a480-dad3-11ea-8ba4-26ef444ff887.png)

**Comment by ghost** [comment]
I see it's a USB 3.0 Host Controller on **Device:**

USB 3 does not work with macOS on VMs, only USB 2.0.

**Comment by mogupta** [comment]
Thankyou. I should just buy a USB 2 host controller instead ? but IPhone and USB Flash drives are working fine ?

**Comment by ghost** [comment]
If you have USB 2.0 ports on the back of the motherboard try connecting them onto there (if any) and then select them one by one on **USB Host Device** after clicking **Add Hardware**.

**Comment by mogupta** [comment]
I don't have USB 2 port on the motherboard. But I tried with USB 3 , it works great. Thankyou. Not sure why the USB controller cannot detect mouse keyboard. It should be plug and play

**Comment by ghost** [comment]
I repeat to you, **macOS** on **VMs does not work** with **USB 3.0**.

**Comment by danyyboi** [comment]
can someone help me to connect iphone to macos kvm.i have qemu running mojave.i have installed virt manager,i dont know how to boot mac os from virt manager and add usb devices.pls somones help me to boot macos from virt manager.i boot with sudo basic.sh

**Comment by ghost** [comment]
> can someone help me to connect iphone to macos kvm.i have qemu running mojave.i have installed virt manager,i dont know how to boot mac os from virt manager and add usb devices.pls somones help me to boot macos from virt manager.i boot with sudo basic.sh

open a new issue
