### ISSUE TITLE
Is possible to increase graphic memory without dedicated GPU?

### ISSUE THREAD

**Issue by shahidcodes** [foxlet/macOS-Simple-KVM#296]
I am using this on a laptop which does not have dedicated graphic card, I got everything working except that graphic memory shows 3 MB. The laptops has octa-core `Intel(R) Core(TM) i7-8565U CPU`. Is there any way to increase the graphics memory without the dedicated GPU?

**Comment by ghost** [comment]
No, as I believe, without a discrete/dedicated GPU, your only option is a **paravirtualized GPU (QXL, VGA or Virtio)**.

**Comment by shahidcodes** [comment]
Thanks @gfelipe099 , can you link any guide for it?

**Comment by ghost** [comment]
That is already set by default by the script

**Comment by shahidcodes** [comment]
So there's no way because default setup shows 3MB graphics, apps like VS Code flickers.

**Comment by ghost** [comment]
in theory you can Passthrough the iGPU but practically I don't know how can it be done

**Comment by ghost** [comment]
It is the same process but you **must** have another GPU to access the host previously.

**Comment by ghost** [comment]
> It is the same process but you **must** have another GPU to access the host previously.

In that case, if you have NVIDIA GPU and intel graphics would it possible to make NVIDA GPU as HOST and passthrough the INTEL Graphics?

**Comment by jerson** [comment]
if you want to use it with catalina or newer versions you should use a dedicated AMD graphics compatible card, im using an Sapphire RX 580

**Comment by jerson** [comment]
NVIDIA GPU is not compatible with newer versions since catalina

**Comment by ghost** [comment]
> > It is the same process but you **must** have another GPU to access the host previously.
> 
> In that case, if you have NVIDIA GPU and intel graphics would it possible to make NVIDA GPU as HOST and passthrough the INTEL Graphics?

Yes, but first check for GPU compatibility on the [OpenCore guide](https://dortania.github.io/OpenCore-Install-Guide/macos-limits.html#gpu-support).
