### ISSUE TITLE
noob question

### ISSUE THREAD

**Issue by ash2osh** [foxlet/macOS-Simple-KVM#3]
i did everything in the guide 
got the other gpu passed through and working :+1: 
BUT 
i cannot use my mouse and keyboard at all [stuck at clover]
tried passing them with 
-device usb-host,hostbus=bus,hostaddr=addr
or 
-device usb-host,hostbus=bus,hostport=port

they are disabled [i think passed] but then the gpu not working [not passed] :(
can you please guide me

**Comment by foxlet** [comment]
What GPU and USB combination are you using?

**Comment by ash2osh** [comment]
my mb is gigabyte 990fxa-ud3 
my gpu is nvidia gt730 2gb ddr3
the usb is on the mb (no external card)
tried etron usb3 port and the amd ports 
no luck

**Comment by foxlet** [comment]
Try updating the packages on your distro, it is possible it could be a QEMU bug.

**Comment by r3d3mpt10n** [comment]
ash2osh: Just press enter at the first screen, it will start booting and once it gets to the MacOS installer page the mouse should be working by then.

**Comment by ash2osh** [comment]
i will try passing the mouse and keyboard from virt-manager


On Tue, 4 Jun 2019, 11:42 a.m. r3d3mpt10n, <notifications@github.com<mailto:notifications@github.com>> wrote:

ash2osh: Just press enter at the first screen, it will start booting and once it gets to the MacOS installer page the mouse should be working by then.

**Comment by ash2osh** [comment]
passing the keyboard and mouse from virt-manager gui worked for me 
i will try to do it from the cli next

NOW i have unreadable verbose boot text then hang 
i am passing through nvidia GT730 ddr3
installed web drivers and activated theme before pass-through
literally banging my head against a wall here :(

**Comment by ash2osh** [comment]
ok still banging my head for garbled graphics 
but was able to pass my mouse and keyboard from cli once after every reboot
