### ISSUE TITLE
What does virtio.sh do?

### ISSUE THREAD

**Issue by xiraix** [foxlet/macOS-Simple-KVM#303]
virtio.sh seems to be very much like basic.sh with a few different flags but I couldn't find any reference to when or how it should be used instead of basic.sh. Can you please clarify this?

**Comment by ghost** [comment]
**virtio.sh** simply uses **VirtIO** instead of **SATA**, which **I personally do not recommend**, since it is **only supported** for **macOS Catalina** and on a **very early stage**.
