### ISSUE TITLE
Big-Sur boot-loop post-install

### ISSUE THREAD

**Issue by Miosame** [foxlet/macOS-Simple-KVM#304]
I've tried to search for solutions or existing filed issues first, but couldn't find anything - after installing and selecting the now installed boot device, the VM gets stuck on `denying core dump for pid XXX` spamming infinitely the screen, never going to an apple boot screen or initial setup.

**Comment by itsvic-dev** [comment]
You'd have to replace the Clover-based ESP with OpenCore.

**Comment by Miosame** [comment]
OSX-KVM already merged the necessary changes: https://github.com/kholia/OSX-KVM closing.
