### ISSUE TITLE
Trying to run XCode, but I need v 10.5 and I have installed 10.4, can I upgrade?

### ISSUE THREAD

**Issue by bulgariamitko** [foxlet/macOS-Simple-KVM#305]
Hello there, 

I want to install XCODE, but in order to install Xcode I need version 10.5 and I have installed 10.4, but trying to upgrade the os I can't do it because it goes into a loop and it is not upgrading. Someone have any advice? Thanks!

**Comment by ghost** [comment]
try fresh install?

**Comment by bulgariamitko** [comment]
I was just following the written instructions. This is my first time installing macos, so I just had to run **./bash** instead of ./bash -mojave or else it will instal 10.14 and with just bash ./bash I will get 10.15.

**Comment by maharramg** [comment]
@bulgariamitko How did you uninstall the vm? Just by deleting the folder?

**Comment by bulgariamitko** [comment]
> @bulgariamitko How did you uninstall the vm? Just by deleting the folder?

Yes. Just delete the folder and start over
