### ISSUE TITLE
Mouse cursor is really jumpy

### ISSUE THREAD

**Issue by jkugler** [foxlet/macOS-Simple-KVM#314]
Install worked
OS boots and works

The mouse, however, is REALLY jumpy. Going backward and forward while trying to move in a given direction.  I searched the issues, but didn't see anything related to this. What could I do to troubleshoot this?

**Comment by ForlornWongraven** [comment]
Just change the mouse to "USB Tablet" in virt-manager.

**Comment by jkugler** [comment]
That works! Also has the advantage of not "capturing" the mouse.

Also: Catalina supports VirtIO! And it's fast! :)

**Comment by hardfire** [comment]
hi
where do you actually change this? My mouse option is empty
![image](https://user-images.githubusercontent.com/513457/95158740-1905f900-07bc-11eb-945a-0a75cabf83d5.png)

**Comment by ForlornWongraven** [comment]
Add device -> Input -> EVTouch USB-Tablet
