### ISSUE TITLE
Volume doesn't show up in Clover to start installation

### ISSUE THREAD

**Issue by ghost** [foxlet/macOS-Simple-KVM#318]
I have a problem and I'm not sure what's the cause.

I have downloaded the master, and copied my own catalina image that I grabbed from my Mac (turned it into ISO from DMG and from there made it IMG with 'dd').

I have followed all the steps except jumpstart.sh, but the result is the title. CLOVER boot manager boots up and the volume doesn't show up.

Configuration:

- Debian 10 Stable

- Kernel: 4.19.0.-10-amd64

- master is in Documents directory and includes the 'BaseSystem.img' and 'mac0S-catalina.qcow2' inside it

![qemu](https://user-images.githubusercontent.com/62484480/94290528-faedfc80-ff62-11ea-9add-fccf741fbca6.png)

**Comment by Nihal2202** [comment]
Facing the same issue.

**Comment by ghost** [comment]
> Facing the same issue.

Did you transfer your own image? I start suspecting that it may be it.

If i figure it myself, I'll let you know!

**Comment by hanslub42** [comment]
I'm having the same issue. I got my ` BaseSystem.img` via `jumpstart.sh`, so that cannot be the problem

**Comment by Nihal2202** [comment]
> I'm having the same issue. I got my ` BaseSystem.img` via `jumpstart.sh`, so that cannot be the problem



> > Facing the same issue.
> 
> Did you transfer your own image? I start suspecting that it may be it.
> 
> If i figure it myself, I'll let you know!

I downloaded it from another website then converted it to _.img_ file, and now got stuck here

**Comment by hanslub42** [comment]
Oh, I should learn to read better. I had _replaced_ the last two lines of `startup.sh`

    -drive id=InstallMedia,format=raw,if=none,file=BaseSystem.img \
    -device ide-hd,bus=sata.3,drive=InstallMedia\
  
with

    -drive id=SystemDisk,if=none,file=MacOS.qcow2 \
    -device ide-hd,bus=sata.4,drive=SystemDisk \

I should have _added_ those last two lines....

**Comment by ph2k** [comment]
@hanslub42 Did this fix the issue?

**Comment by hanslub42** [comment]
Yes.

**Comment by ghost** [comment]
@NihalP01 did you try to download the image via jumpstart, and if so did it fix it?

I'm planning on downloading it again that way, and see if the volume appears.

**Comment by Nihal2202** [comment]
@engineer22 okay If you are downloading then please inform me and tell me if the problem is solved or not. It is not possible for me actually to download it again as I have very low speed connection and limited data. :-p

**Comment by ghost** [comment]
@NihalP01 got it, I'll let you know.

**Comment by Nihal2202** [comment]
> @NihalP01 got it, I'll let you know.

    Did your issue get solved bro?

**Comment by ghost** [comment]
@NihalP01 hey man, I am away from my test bench this week so I cannot do it right now.

When I do it I will give you feedback. If you tesy it let me know too.

**Comment by singhamitoj** [comment]
I think I know the answer to the problem. BaseSystem.dmg might be corrupt, or you have the wrong file, so check your BaseSystem.img and BaseSystem.dmg and see if that is the problem. I deleted my BaseSystem.dmg and BaseSystem.img, and ran fetch-macos.py -l to get the Mojave installer, and it worked!

**Comment by Nihal2202** [comment]
okay, I think the problem is in the externally downloaded dmg file. Have to  check running the fatch-macos.py

**Comment by ghost** [comment]
@NihalP01 I'll be testing in an hour with jumpstart. I'll update you later today!

**Comment by ghost** [comment]
@NihalP01 UPDATE: the volume is visible with jumpstart.

You need to download it this way, unfortunately. It can take time if you don't have fast internet connection, but I don't have time to troubleshoot.

For me the image downloaded in one minute.

**Comment by Nihal2202** [comment]
> @NihalP01 UPDATE: the volume is visible with jumpstart.
> 
> You need to download it this way, unfortunately. It can take time if you don't have fast internet connection, but I don't have time to troubleshoot.
> 
> For me the image downloaded in one minute.

@engineer22 did your issue get solved now? 
Yeah, I have 1MBps speed with limited data so this will take eternity  (•‿•)

**Comment by ghost** [comment]
@NihalP01 oof, then it will indeed take countless hours.

Yes it worked. If I have time, I may take a look and try to troubleshoot so you can import the IMG instead of downloading.

**Comment by Nihal2202** [comment]
@engineer22 it's great bro! Thank you for the information. Will try it one day for sure..now enjoy your mac XD

**Comment by Dustylab** [comment]
> Oh, I should learn to read better. I had _replaced_ the last two lines of `startup.sh`
> 
> ```
> -drive id=InstallMedia,format=raw,if=none,file=BaseSystem.img \
> -device ide-hd,bus=sata.3,drive=InstallMedia\
> ```
> 
> with
> 
> ```
> -drive id=SystemDisk,if=none,file=MacOS.qcow2 \
> -device ide-hd,bus=sata.4,drive=SystemDisk \
> ```
> 
> I should have _added_ those last two lines....

Works for me also ...
