### ISSUE TITLE
[Docs] Required disk space?

### ISSUE THREAD

**Issue by geckolinux** [foxlet/macOS-Simple-KVM#32]
Hi there, roughly how much free disk space do I need for an installation? I see it recommends creating a 64GB qcow, but what would the bare minimum be? And what about the MacOS installer image download size?

**Comment by foxlet** [comment]
Bare minimum would be around 20GB, but you'll find it hard to get any apps installed (like Xcode, which is at least 8GB compressed).

**Comment by geckolinux** [comment]
Got it, thanks very much for the quick response.

**Comment by foxlet** [comment]
The jumpstart download is ~500MB compressed (2GB uncompressed), the installation files are uncompressed and measure 6.5GB.
