### ISSUE TITLE
GPU passthrough not booting OS, claims that there's no file or directory. I copied the command from your guide

### ISSUE THREAD

**Issue by maggster165** [foxlet/macOS-Simple-KVM#329]
So I just installed Mojave. Performance is excellent, but it is quite choppy and laggy. I tried to do the gpu passthrough thing, but it says there's no file or directory. Can you help me? As this works quite well and I want to try out the full macOS experience. However, with no gpu acceleration, it runs great but looks laggy and animations are choppy.

**Comment by xD3CODER** [comment]
Try to put your patched rom file inside `/var/lib/libvirt/`

**Comment by maggster165** [comment]
Well, I found out that my cpu and gpu both support passthrough, but it's not in my bios and I have to install coreboot on the laptop to enable iommu functionality, but that's a no go. Is there a way to at least speed the VM up to remove some lag? It's working well but the cursor is laggy and moving windows is laggy too. (EDIT: I'm currently writing this from macOS and tried installing a Mac OS qxl driver. It helped a bit with the mouse but not much. I just want the macOS experience and so I'm gonna try pearOS if this isn't gonna work well. It also made videos work well, but still no audio)

**Comment by Genxster1998** [comment]
@Kubamach Better move to Hackintosh if you really want native near performance
