### ISSUE TITLE
[Question] Sustainability of method?

### ISSUE THREAD

**Issue by geckolinux** [foxlet/macOS-Simple-KVM#33]
Very cool project! So if I understand the `fetch-macos.py` script correctly, it seems to pull the macOS image directly from Apple's CDN? That is more robust than I expected, figured it would just be a third party server that Apple could quickly get taken down. But with that being said, I see the script needs a `User-Agent` to connect to the Apple CDN and SDS; couldn't Apple quickly revoke that apparently anonymous useragent?

**Comment by deftdawg** [comment]
They could, then a new way would have to be found....  why are you opening an issue for this?

**Comment by geckolinux** [comment]
I like to know how stuff works and if I could potentially use something like this in the long term. But feel free to delete this issue if you think it's out of place or risky to your project.

**Comment by foxlet** [comment]
The string comes from the actual macOS Installer app as distributed on the App Store (and has been distributed for many years). If they banned the User-Agent they would also ban all the existing macOS Installers on legitimate Macs.

**Comment by geckolinux** [comment]
Interesting, thanks for the explanation. Again, feel free to delete this issue if you think it will cause problems.
