### ISSUE TITLE
RHEL/CentOS 8 Support?

### ISSUE THREAD

**Issue by ecnepsnai** [foxlet/macOS-Simple-KVM#332]
RHEL/CentOS 8 doesn't provide any `qemu-system-x86_64` binary, so none of the scripts offered here work there.

CentOS support seems to be spotty. It's mentioned as being 'problematic' in this comment: https://github.com/foxlet/macOS-Simple-KVM/issues/167#issuecomment-589940151 

@prghix asked about EL8 support back in January but doesn't look like anybody chimed in: https://github.com/foxlet/macOS-Simple-KVM/issues/110#issuecomment-571570993

**Comment by ecnepsnai** [comment]
I'm going to wager that it's a big no as Redhat disabled the applesmc device in qemu.

**Comment by Provissy** [comment]
You can refer to my reply in https://github.com/foxlet/macOS-Simple-KVM/issues/167#issuecomment-748871634
