### ISSUE TITLE
Error message "Failed to initialize module: /usr/lib/x86_64-linux-gnu/qemu/*.so"

### ISSUE THREAD

**Issue by malown** [foxlet/macOS-Simple-KVM#336]
I get the following output at step 2 when I run basic.sh

> Failed to initialize module: /usr/lib/x86_64-linux-gnu/qemu/ui-gtk.so
> Note: only modules from the same build can be loaded.
> Failed to initialize module: /usr/lib/x86_64-linux-gnu/qemu/audio-pa.so
> Note: only modules from the same build can be loaded.
> Failed to initialize module: /usr/lib/x86_64-linux-gnu/qemu/audio-pa.so
> Note: only modules from the same build can be loaded.
> VNC server running on ::1:5900

From there on nothing happens
_________________________

OS: Pop_OS 20.04

**Comment by malown** [comment]
> sudo apt install qemu-system-x86

Fixed it

**Comment by finnmerlett** [comment]
That nailed it, thank you so much

**Comment by redface25** [comment]
how did you fix it?????

**Comment by redface25** [comment]
> how did you fix it?????

dont worry iam a bit dumb

**Comment by 0Armaan025** [comment]
hi! i might be a bit late, but i i need help too 😢

**Comment by rock3tsprocket** [comment]
> Fixed it

would you be so kind as to say how you fixed it

**Comment by finnmerlett** [comment]
Just run the command they quoted!

```sudo apt install qemu-system-x86```

**Comment by rock3tsprocket** [comment]
> Just run the command they quoted!
> 
> `sudo apt install qemu-system-x86`

ah right i didn't notice, whoops. i gave up on fixing my issue anymore though
