### ISSUE TITLE
Mouse is behaving erratically

### ISSUE THREAD

**Issue by sirka0s** [foxlet/macOS-Simple-KVM#342]
Hello!

After installing Catalina, I am having some mouse issues - I already tried three different mouse and vendors and it is still the same. Mouse is occasionally hitting imaginary "walls", moves from place to place without my input and so on.

All settings are default apart from resolution - it is set to 2560x1440 (but issue was the same whilst it was default 1280x760).

Thanks!

**Comment by bolapara** [comment]
[This suggestion](https://github.com/foxlet/macOS-Simple-KVM/issues/168#issue-570311571) helped me.

**Comment by sirka0s** [comment]
That did it, thanks! 

Issue resolved.
