### ISSUE TITLE
Cores for Ryzen?

### ISSUE THREAD

**Issue by kaihendry** [foxlet/macOS-Simple-KVM#345]
https://github.com/foxlet/macOS-Simple-KVM/blob/master/docs/guide-performance.md

I'm not sure how `    -smp 4,cores=2 \` translates to my Ryzen

[cpuinfo.txt](https://github.com/foxlet/macOS-Simple-KVM/files/5455887/cpuinfo.txt)

Any tips?

**Comment by goshawk22** [comment]
Set cores to the number of cores you want to give the virtual machine. My Ryzen 7 1700 has 8 cores, so I set this to 8. A ryzen 5 will have 6 cores and a Ryzen 3 will have 4 cores.
All ryzen CPUs support smp so you should set this to double the value for cores.

**Comment by kaihendry** [comment]
So IIUC, upon my **AMD Ryzen 7 PRO 4750U Processor** I have `grep processor /proc/cpuinfo  | wc -l` 16 cores. So if I wanted to give the VM so _all_ my compute power, I would do something like:

`-smp 32,cores=16 \`  ... correct?

**Comment by goshawk22** [comment]
The AMD Ryzen 7 PRO 4750U has 8 cores and 16 threads. Therefore the maximum values you could assign would be 
`-smp 16 cores=8`
You should also look at #319 if you have any problems assigning more cores.

**Comment by kaihendry** [comment]
Thanks! any tips wrt GPU ids? https://github.com/foxlet/macOS-Simple-KVM/issues/346
