### ISSUE TITLE
State minimum version of QEMU

### ISSUE THREAD

**Issue by adrianlshaw** [foxlet/macOS-Simple-KVM#35]
The macOS installer doesn't fully boot with QEMU on Debian Stable (stretch), which makes me think that the version in the repos is too old. Would be good to know which version has the necessary fixes for booting.

**Comment by foxlet** [comment]
QEMU 3.1.x or later is recommended, with 2.12 being the absolute minimum (with some bugs).

**Comment by deftdawg** [comment]
QEMU emulator version 2.11.1(Debian 1:2.11+dfsg-1ubuntu7.14) works with patch #38

**Comment by Enrico204** [comment]
@adrianlshaw Debian stable has 2.8 unfortunately - I tried to backport 3.1 from testing but there is some issues with debhelper. I'll try to fix it. Or perhaps we can wait a few more days for Debian 10 :-D

**Comment by adrianlshaw** [comment]
Thanks @foxlet and @deftdawg.

> Or perhaps we can wait few more days for Debian 10 :-D

Didn't know about the release! I'll just kick back for a couple of weeks then :-)

**Comment by Enrico204** [comment]
@adrianlshaw I managed to compile `qemu` version 4 from source on my Debian 9 installation, and it works like a charm :-)
(I changed `basic.sh` to use the compiled version of `qemu` as I didn't want to overwrite the packaged version)
PS: for `qxl` video driver you'll need SPICE libraries
