### ISSUE TITLE
MyDisk.qcow2 Permission denied

### ISSUE THREAD

**Issue by hericiumvevo** [foxlet/macOS-Simple-KVM#350]
All my files are in /home/jasio/macOS-Simple-KVM/ and every time I try to boot the VM this happens:
```
Error starting domain: Cannot access storage file '/home/jasio/macOS-Simple-KVM/MyDisk.qcow2' (as uid:65534, gid:992): Permission denied

Traceback (most recent call last):
  File "/usr/share/virt-manager/virtManager/asyncjob.py", line 75, in cb_wrapper
    callback(asyncjob, *args, **kwargs)
  File "/usr/share/virt-manager/virtManager/asyncjob.py", line 111, in tmpcb
    callback(*args, **kwargs)
  File "/usr/share/virt-manager/virtManager/object/libvirtobject.py", line 66, in newfn
    ret = fn(self, *args, **kwargs)
  File "/usr/share/virt-manager/virtManager/object/domain.py", line 1279, in startup
    self._backend.create()
  File "/usr/lib/python3.8/site-packages/libvirt.py", line 1234, in create
    if ret == -1: raise libvirtError ('virDomainCreate() failed', dom=self)
libvirt.libvirtError: Cannot access storage file '/home/jasio/macOS-Simple-KVM/MyDisk.qcow2' (as uid:65534, gid:992): Permission denied
```
Can somenone help?

**Comment by Tiebe** [comment]
Did you set the right permissions on the file?

**Comment by hericiumvevo** [comment]
> Did you set the right permissions on the file?

I searched that error on google and someone used root:root on the file and root in /etc/libvirt/qemu.conf, and someone else used their username as user and group in config and their username as file owner and group. Both didn't work for me and the file has 
```
owner: root
group: root 
```
by default.
I seen people use qemu-libvirt group (or something like this) but it doesn't exist for me.

**Comment by Tiebe** [comment]
Try running 
`chmod ugo+rwx MyDisk.qcow2`

**Comment by hericiumvevo** [comment]
I reinstalled my whole distro and it fixed evrything.
