### ISSUE TITLE
Error starting domain: operation failed: unable to find any master var store for loader: /home/jasio/macOS-Simple-KVM/firmware/OVMF_CODE.fd

### ISSUE THREAD

**Issue by hericiumvevo** [foxlet/macOS-Simple-KVM#352]
```
Error starting domain: operation failed: unable to find any master var store for loader: /home/jasio/macOS-Simple-KVM/firmware/OVMF_CODE.fd

Traceback (most recent call last):
  File "/usr/share/virt-manager/virtManager/asyncjob.py", line 75, in cb_wrapper
    callback(asyncjob, *args, **kwargs)
  File "/usr/share/virt-manager/virtManager/asyncjob.py", line 111, in tmpcb
    callback(*args, **kwargs)
  File "/usr/share/virt-manager/virtManager/object/libvirtobject.py", line 66, in newfn
    ret = fn(self, *args, **kwargs)
  File "/usr/share/virt-manager/virtManager/object/domain.py", line 1279, in startup
    self._backend.create()
  File "/usr/lib/python3/dist-packages/libvirt.py", line 1234, in create
    if ret == -1: raise libvirtError ('virDomainCreate() failed', dom=self)
libvirt.libvirtError: operation failed: unable to find any master var store for loader: /home/jasio/macOS-Simple-KVM/firmware/OVMF_CODE.fd
```
The file exists but for some reason I get this error.

**Comment by kurtis318** [comment]
I am also getting this same error.  I am running on Fedora 33 KDE Workstation.  My OVMF_CODE.fd file was originally in my home directory but I copied the file to /var/lib/libvirt/images and used virsh edit <guest-name> to change the path to the file.  I also have sELINUX disabled.  This was working on Fedora 32.  Thanks...

**Comment by hericiumvevo** [comment]
> I am also getting this same error. I am running on Fedora 33 KDE Workstation. My OVMF_CODE.fd file was originally in my home directory but I copied the file to /var/lib/libvirt/images and used virsh edit to change the path to the file. I also have sELINUX disabled. This was working on Fedora 32. Thanks...

before moving to virt-manager you need to backup firmware folder
