### ISSUE TITLE
Problem with Display, even without Graphics Card

### ISSUE THREAD

**Issue by unloopedmido** [foxlet/macOS-Simple-KVM#383]
So whenever I start my virtual machine, Clover menu looks normal, everything looks normal
![image](https://user-images.githubusercontent.com/73798815/102017819-3508b680-3d7a-11eb-974b-ad7def2be008.png)
But then this happens to the display
![image](https://user-images.githubusercontent.com/73798815/102017828-418d0f00-3d7a-11eb-82e4-cbd60659728c.png)

**Comment by Jerit3787** [comment]
Before this, were you able to see macos desktop?

**Comment by ipatch** [comment]
i've run into this issue from time to time. it cropped up on me (no pun) when launching my VM (mojave) using the headless shell script and using vnc to launch the graphical display for the VM. i then switched back to the standard basic shell script and this display rendering irregularities went away, and then used my headless shell script again started working.

on a side note these issues did arise after i started messing around with the config.plist stored on the EFI partition when i started experimenting with different screen resolutions so make sure to read the adjusting screen resolution doc within this repo.

**Comment by unloopedmido** [comment]
> Before this, were you able to see macos desktop?

yes
