### ISSUE TITLE
Audio crashes when using microphone

### ISSUE THREAD

**Issue by jcrowthe** [foxlet/macOS-Simple-KVM#384]
I had a curious issue I wanted to report on, in case others run into similar issues.

I used this repository to build a MacOS virtual machine, and managed it with virt-manager. Audio output works without issue but whenever an app attempts to use the microphone, I would experience weird glitchy errors such as the following:
- Console would print lots of audio related logs, the following two of which seemed most indicative of an issue:
```
USB Sound assertion (Resetting engine due to error returned in Write Handler) in /AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/AppleUSBAudio/AppleUSBAudio-323.4/AppleUSBAudioDevice.cpp at line 6617
USB Sound assertion (Resetting engine due to error returned in Read Handler) in /AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/AppleUSBAudio/AppleUSBAudio-323.4/AppleUSBAudioDevice.cpp at line 6609
```
- Audio drivers may crash whatever program was attempting to use the microphone (Chrome, Zoom, Quicktime). Alternatively, the app would become unresponsive with a spinning beachball
- Audio _output_ would immediately stop if previously playing music or a video
- If attempting to record sound, such as with Quicktime, the microphone may pick up a split second of noise before going silent for the duration of the recording. Alternatively, the recording may not be made at all and Quicktime will say it failed to capture any data.

Curiously when going to System Preferences > Sound > Input and viewing the input visualization bars, the microphones I tested would be super responsive. However once attempting to use any application to utilize a microphone, I'd get the above symptoms.

Setup:
- Utilizing vfio, I passed through a USB controller and am only using passed-thru USB devices
- Tested with two devices:
  - HyperX Quadcast external USB microphone
  - Logitech webcam with built-in microphone.

**Solution:**
My issue appears to be be found in the fact that I was using a USB hub built into my Dell monitor. When the microphone is plugged into the monitor's USB hub (which is in turn plugged directly into the back of my desktop) I experience these issues. However when plugging the microphones directly into my desktop's passed-thru USB controller, the issues disappear.

Anyway, I thought I'd contribute this back. Thanks all for the great work in this repo!

**Comment by sahilrajput03** [comment]
How did you connect the microphone.? Can you please help me.. on that with that..?
