### ISSUE TITLE
Resolution messing up after starting with Virt-Manager?

### ISSUE THREAD

**Issue by Matthew-Tate-Scarbrough** [foxlet/macOS-Simple-KVM#398]
Starting with `basic.sh` works perfectly, but when I boot using `Virt-Manager` Clover is fine but actually trying to boot the OS causes three duplicate, 'de-interlaced' images of low quality that overlap, stretched across the screen.

It is worth noting that when using the base resolution, all is well in Virt-Manager.
But my main monitor is 1080p, so...

![Screenshot_20210106_213524](https://user-images.githubusercontent.com/52991977/103848038-1a6aea00-5067-11eb-8d7d-bddabd4ff7cf.png)

![Screenshot_20210106_213548](https://user-images.githubusercontent.com/52991977/103848057-25be1580-5067-11eb-903b-85c3d9b849ab.png)

- - - -

# EDIT:
It turns out that the solution was to start up the VM with `./basic.sh`, press escape and enter `exit` in the UEFI shell.
I am using Catalina, so I had to tab to `> Device Manager`, then tab down to `> OVMF Platform Configuration` and manually set the resolution, then save with `F10`, and poweroff, then start with Virt-Manager.

**Comment by bourne-against** [comment]
I was having the same problem but found the solution here: [https://github.com/foxlet/macOS-Simple-KVM/issues/51#issuecomment-504503903](url)

**Comment by Matthew-Tate-Scarbrough** [comment]
> I was having the same problem but found the solution here: [https://github.com/foxlet/macOS-Simple-KVM/issues/51#issuecomment-504503903](url)

That comment link is broken, but I went to Issue #51 and found what I needed, thank you.
