### ISSUE TITLE
Will this work on NVidia GeForce 940MX GPU?

### ISSUE THREAD

**Issue by kneelesh48** [foxlet/macOS-Simple-KVM#4]
Will it? Or do I have to disable the Graphics card? Thank you!

**Comment by kneelesh48** [comment]
Does this only work on GPUs found in Macs?

**Comment by foxlet** [comment]
PCIe passthrough only works with GPUs supported by macOS (either natively or through downloadable web drivers). Software Graphics works on any machine but is much slower (only text and images, no video or OpenGL).

**Comment by midi1996** [comment]
GT940MX is probably a headless GPU, and will probably not work due to the lack of any output ports, even if you install the webdrivers.
