### ISSUE TITLE
can i use the .img file on my laptop (non apple hardware) hp probook 640 g1

### ISSUE THREAD

**Issue by Sambhrama754** [foxlet/macOS-Simple-KVM#403]

**Comment by Sambhrama754** [comment]
I mean uninstalling Linux and install Mac OS

**Comment by Mythbusters123** [comment]
You would have to install open core/clover to get it to run, and then convert the .img to an .iso.

**Comment by SomethingGeneric** [comment]
@Sambhrama754 look into OpenCore if you want to run on real hardware. IIRC they're the most active in terms of making PC grade hardware work with MacOS

**Comment by Sambhrama754** [comment]
ok
