### ISSUE TITLE
Not working on a VM

### ISSUE THREAD

**Issue by mikyjet06** [foxlet/macOS-Simple-KVM#404]
Hey guys I have been trying out this on a Ubuntu VM, because I don't have a Linux PC right now. Does this work on a VM because when I run basic.sh I get an error saying: 

`Could not access KVM kernel module: No such file or directory ;
qemu-system-x86_64: failed to initialize KVM: No such file or directory`

**Comment by Masamune3210** [comment]
Likely no, not sure about nested virtualization and its limits, but running a VM inside of a VM absolutely murders performance so it's likely not worth even trying honestly

**Comment by SomethingGeneric** [comment]
I'd be surprised if it's ever been/will be possible to use Hyper-V to host KVM to run QEMU.

@mikyjet06 why not just dual boot Ubuntu, or better yet, a lighter version like Debian?
