### ISSUE TITLE
Using Machine with 'real' Apple-ID?

### ISSUE THREAD

**Issue by herbertvonkaramalz** [foxlet/macOS-Simple-KVM#411]
As a proud owner of a MacBook, an iPhone and an Apple Watch i would like to create a DIY-Mac-Device using my old Workstation.

But i am not sure, if it is possible or a good idea to log in in this machine using my default Apple-ID i am using on other Devices?
Will Apple see, that the Device is not authorized and what could happen in worst-
case?

Did anyone tried to do so?

Cheers!

**Comment by Mythbusters123** [comment]
As far as I know, all you have to do is spoof the Serial Number and MAC address. The worst thing that can happen is a soft ban BTW.

**Comment by herbertvonkaramalz** [comment]
@Mythbusters123 Thanks for your Answer :-)
