### ISSUE TITLE
Switch to Docker

### ISSUE THREAD

**Issue by bclermont** [foxlet/macOS-Simple-KVM#414]
Why you don't use build docker image that have all steps in portable containers? that might simplify a lot everything, no?

**Comment by tbrtje** [comment]
No, what would that help? There is nothing that needs to be built.

**Comment by Joseph-Hui** [comment]
You can check [this](https://github.com/sickcodes/Docker-OSX).

**Comment by walker84837** [comment]
@jeanlucmongrain I think using Docker or anything to build is kind of pointless in repos like this. Yes, you can point a symlink in `/usr/bin` to match the `basic.sh` or make a script that does the `jumpstart.sh` and `basic.sh` part all-in-one for speed purposes, but I think it's just better to keep it simple and let it be as is.
