### ISSUE TITLE
deleted 

### ISSUE THREAD

**Issue by bbabou** [foxlet/macOS-Simple-KVM#422]
deleted

**Comment by KeetKhat** [comment]
If you use virsh you can type the command "sudo virsh autostart [VM_NAME]". If you don't use virsh you can create a systemd service to start the qemu script at boot

**Comment by jadou7** [comment]
Thanks @KeetKhat, is it possible to disable the Linux GUI ?

**Comment by KeetKhat** [comment]
Follow this tutorial https://gitlab.com/Karuri/vfio
If you got an AMD GPU you don't need to disable the EFI framebuffer

**Comment by jadou7** [comment]
Thanks a lot, if I have more question, I'll recontact you.
