### ISSUE TITLE
Can't configure virt-manager

### ISSUE THREAD

**Issue by OmkoBass** [foxlet/macOS-Simple-KVM#433]
Can anyone help me boot macos with virt-manager. I added the BaseSystem.img as the OS and added MyDisk.qcow2 as the storage. I also executed the ``` ./jumpstart.sh -add ``` but it's virt-manager is still stuck on on "Booting".

**Comment by OmkoBass** [comment]
Fixed it.

- ```sudo ./make.sh --add``` in the repo you cloned
- You will get a template.xml, that template is needed to create the virtual machine
- Create a virtual machine and replace it's xml config with the one that was generated with the command above 

If you still have problems with master var, then check this issue out #395

**Comment by artforlife** [comment]
How do you boot into the system after adding it to Virt Manager? I seem to get a screen in Clover that does not contain the OS I have already installed. I did add my .qcow image to the VM created in `sudo ./make.sh --add` step.

I have also gotten "Not a bootable disk" and "Booting" when playing with the settings.

**Comment by OmkoBass** [comment]
Create a virtual machine in Virt Manager, add the XML config file that's generated from the macOS-Simple-KVM to the Virt Manager virtual machine and then run it.
