### ISSUE TITLE
qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.01H:ECX.pcid [bit 17]

### ISSUE THREAD

**Issue by Robin-Sch** [foxlet/macOS-Simple-KVM#449]
Got this error when starting in Virtual Machine Manager
CPU: AMD Ryzen 5 4600G

**Comment by Robin-Sch** [comment]
I just deleted everything, and remade it.  That fixed it.

**Comment by LimitlessDonald** [comment]
Hello @Robin-Sch I know this is old, but how did you get it to run. Can you share your basic.sh file ?

I have a similar processor , I am stuck at setting 1 core and 1 thread, in my basic.sh file. If I set anything greater than that, macOs won't boot .

Appreciate your help, thanks .

**Comment by Robin-Sch** [comment]
I don't have the file anymore, so I'm unsure. What I did is that I deleted everything and redid all the steps (afaik) and then it worked. You should try that aswell, and if it still does not work open a new issue I guess.

**Comment by sfjuocekr** [comment]
Maybe a little late but if you use virtio for display, disable 3D acceleration.
