### ISSUE TITLE
sudo: ./basic.sh: command not found

### ISSUE THREAD

**Issue by jaikhuranna** [foxlet/macOS-Simple-KVM#459]
im running manjaro 21.04

output to ./basic.sh

bash: ./basic.sh: Permission denied

output to sudo ./basic.sh

sudo: ./basic.sh: command not found

**Comment by SuperSandro2000** [comment]
``chmod +x basic.sh`` and do you have ``/bin/bash`` in your system?

**Comment by jaikhuranna** [comment]
no

**Comment by jaikhuranna** [comment]
thanks
it works now
I did  chmod -x ./basic.sh before registering this issue.
