### ISSUE TITLE
cant sudo  ./make.sh --add

### ISSUE THREAD

**Issue by jaikhuranna** [foxlet/macOS-Simple-KVM#461]
output for sudo ./make.sh --add
`
template.xml has been generated in /home/jaik/macOS-Simple-KVM-master
error: failed to connect to the hypervisor
error: Failed to connect socket to '/var/run/libvirt/libvirt-sock': No such file or directory
`

**Comment by jaikhuranna** [comment]
virt-manager is instaled

**Comment by yavincl** [comment]
```
systemctl disable --now libvirtd
systemctl enable --now libvirtd.socket
systemctl enable --now libvirtd
```

**Comment by jaikhuranna** [comment]
thanks, i changed distros
