### ISSUE TITLE
Cant launch the VM 

### ISSUE THREAD

**Issue by mei1212123** [foxlet/macOS-Simple-KVM#464]
after creating the QCOW2 File and adding the 2 lines at the bottom to basic.sh then when i try to launch it brings this up qemu-system-x86_64:  : Could not open ' ': No such file or directory
./basic.sh: line 29: -drive: command not found

**Comment by urrstupid-bob** [comment]
i have that same error too

**Comment by mei1212123** [comment]
i dunno how but reinstalling qemu and virt manager worked

**Comment by urrstupid-bob** [comment]
i dont remember installing virt-manager so that might be the problem

**Comment by urrstupid-bob** [comment]
hey what linux do you use because i want to see if it works on a specific linux

**Comment by mei1212123** [comment]
it works on any distro
