### ISSUE TITLE
How do I pass my usb through to Mac 

### ISSUE THREAD

**Issue by Daszbin** [foxlet/macOS-Simple-KVM#475]
I am running Manjaro Linux with Mac OS Catalina running on QEMU how am I able to pass through a usb device on Linux to QEMU so Mac can recognize it. Meaning if I plug in a usb to Linux so Mac can detect it.

**Comment by mikocevar** [comment]
There are already a number of discussions about this, did you try to google the issue first? Here are some links, some of them are linking back to this repo.

https://www.gitmemory.com/issue/foxlet/macOS-Simple-KVM/37/511158055
https://null-src.com/posts/qemu-vfio-pci/post.php
https://www.linuxquestions.org/questions/blog/kingbeowulf-74138/qemu-usb-passthrough-with-specifics-for-iphone-37830/
https://stackoverflow.com/questions/52617634/how-do-i-get-qemu-usb-passthrough-to-work-for-ipad-iphone
https://github.com/foxlet/macOS-Simple-KVM/issues/221
https://github.com/sickcodes/Docker-OSX/issues/36

Between these links you'll find references between all links i gave you. Please do a research before asking questions that already might be answered or have a topic open.
