### ISSUE TITLE
Exec format error

### ISSUE THREAD

**Issue by fushiwara-risu** [foxlet/macOS-Simple-KVM#478]
When running jumpstart.sh I get an error at the end saying that dmg2img failed to execute "Exec format error"
I am on Windows10
![image](https://user-images.githubusercontent.com/57734346/122693226-cf482c00-d1ed-11eb-950c-5f03117d8dc9.png)

**Comment by fushiwara-risu** [comment]
After a few hours of trying, now that I have posted this I think I have the solution...
I downloaded the tool and ran it that way

**Comment by Hadesunjackd** [comment]
Can you elaborate a bit
