### ISSUE TITLE
How to edit SMC

### ISSUE THREAD

**Issue by DeadlyMelqn** [foxlet/macOS-Simple-KVM#48]
My goal: iMessage and such.

This is done in virtualbox to show smbios info: https://github.com/toshmatik/VMWare-iMessage/blob/master/instructions.md

How can I do this here?

**Comment by foxlet** [comment]
iMessage is already compatible, you only need to provide SMBIOS data to Clover with a compatible serial number and MLB. The configuration is in the `EFI` partition at `\EFI\Clover\config.plist`.

**Comment by DeadlyMelqn** [comment]
I've tried multiple guides for clover config, anything different u did?

**Comment by foxlet** [comment]
No, just make sure you didn't get your account banned in the attempts to get it working.

**Comment by sreehax** [comment]
Is there a guide on everything i need to do to get iMessage working? Currently when I try to sign in to iMessage i get the "You cannot sign in to iMessage on this mac at this time." error. I even tried using a new apple id. I tried to change the serial number using clover configurator already. I'm using virt-manager if that matters. thanks.
