### ISSUE TITLE
error "bash: ./jumpstart.sh: Permission denied" when trying to run jumpstart.sh

### ISSUE THREAD

**Issue by rubybirdy** [foxlet/macOS-Simple-KVM#482]
the title is pretty much all, currently running elementary OS 6 beta 2 (built on ubuntu 20.04.1 LTS)

![Screenshot from 2021-06-28 12-47-27](https://user-images.githubusercontent.com/79671269/123681145-0da5a280-d80f-11eb-908c-47ca285b5fb4.png)

**Comment by kristian-oliveira** [comment]
Hi @rubybirdy, Congratulations on opening your first issue! You lack the permissions to run this script. To remedy this run the script _jumpstart.sh_ as a superuser using the _sudo_ command: `sudo ./jumpstart.sh`. Consult the man pages for more information on the _sudo_ command:  `man sudo`.
