### ISSUE TITLE
error says confusing things about segmentation issues and a non-existent line 31

### ISSUE THREAD

**Issue by rubybirdy** [foxlet/macOS-Simple-KVM#483]
i boot qemu successfully but after a bit of installation i get this confusing message. there's no line 31 in my basic.sh and i have no idea what segmentation could mean, any help?

![Screenshot from 2021-06-28 17-04-12](https://user-images.githubusercontent.com/79671269/123709548-e19c1880-d832-11eb-95e5-c0e02b054209.png)

![Screenshot from 2021-06-28 16-56-28](https://user-images.githubusercontent.com/79671269/123709254-5d499580-d832-11eb-9e0e-1551c0171245.png)

**Comment by nerve-hawthorne** [comment]
1. Full path to your `SystemDisk` looks strange to me, just use `file=MyDisk.qcow2`.
2. Execute `basic.sh` with sudo.
3. Tell us more about when you get the segfault.
