### ISSUE TITLE
Mouse and Keyboard (USB Passthrough) not working

### ISSUE THREAD

**Issue by WakanaYuki** [foxlet/macOS-Simple-KVM#487]
So my mouse and keyboard aren't working. They are correctly referenced (as this exact config has worked on another Distro before). The only problem is that my mouse and keyboard cease to work after the boot manager. Everything works fine in the boot manager, but at the login screen neither my Keyboard nor my mouse is working at all. 

They are both USB 2.0.

**Comment by nick-tonjum** [comment]
what was your solution?
