### ISSUE TITLE
virt-manager start error

### ISSUE THREAD

**Issue by odinggg** [foxlet/macOS-Simple-KVM#49]
after `make.sh --add` 
start virt-manager 
error:internal error: process exited while connecting to monitor: 2019-06-21T07:59:27.954130Z qemu-system-x86_64: -machine pc-q35-3.0,accel=kvm,usb=off,vmport=off,dump-guest-core=off: unsupported machine type 'pc-q35-3.0'
Use -machine help to list supported machines

system:ubuntu18.04

**Comment by deftdawg** [comment]
See #38

**Comment by deftdawg** [comment]
#54 fixes this...  or you can manually go in and edit the machine using virtsh to replace pc-q35-3.0 with q35
