### ISSUE TITLE
Could not connect to recovery server

### ISSUE THREAD

**Issue by Denzy7** [foxlet/macOS-Simple-KVM#495]
I've managed to import the vm into virt-manager but when it's booted, I click Reinstall  MacOS and I get an error could not connect to recovery server. I'm using arch, X and dwm

**Comment by Comonito** [comment]
> 

I was having the same issue earlier. Installing bridge-utils solved fixed it for me.

**Comment by Denzy7** [comment]
Yep now it works. Look's like I was installing without internet or bridge-utils. Thanks dude
