### ISSUE TITLE
Cant install Xcode version 11 or later is required.

### ISSUE THREAD

**Issue by Aterox-os** [foxlet/macOS-Simple-KVM#498]
Hi, yesterday I managed to install simple KVM on my Ubuntu machine. I running Mac OS Catalina version 10.15.7. Now I want to install Xcode from the App Store, but when I try to install it I get an error "Xcode can't be installed on "Mydisk" because macOS version 11 or later is required". When I go in the settings to update the system, I can only install MacOS BigSur. When I start it and let it run, the system reboots and starts from the beginning. What can I do?

**Comment by Berstanio** [comment]
Every XCode above 12.4 requieres MacOS Big Sur. There isn't a way around this that I know. So you could try to setup a vm running MacOS Big Sur (maybe check here the BigSur branch?) or you install XCode 12.4 manually. You can download it here: https://developer.apple.com/download/all/
