### ISSUE TITLE
Mouse not moving upwards

### ISSUE THREAD

**Issue by muffinmaster1024** [foxlet/macOS-Simple-KVM#501]
Everything worked fine so far. Installed Catalina on Ubuntu 20.04 LTS.

Atm the VM is basically unusable because I'm not able to move the mouse/cursor upwars.
Down, left and right works but not up... pretty dumb situation

Any help would be appreciated!

**Comment by darkstego** [comment]
I had the same problem, but when I switched to virt-manager it now doesn't move right  and moves in every other direction.

Fix was replacing USB mouse with USB tablet

-usb -device usb-kbd -device usb-mouse \

to

-usb -device usb-kbd -device usb-tablet \


or in Virt-manager deleting usb mouse and installing usb tablet

**Comment by muffinmaster1024** [comment]
Wow, thanks a lot! Works flawlessly now!
