### ISSUE TITLE
jumpstart cannot exe binary file; format error on Rasberry Pi, Ubuntu server with DE

### ISSUE THREAD

**Issue by Cohen-Koen** [foxlet/macOS-Simple-KVM#506]
Here is the direct error: ```./jumpstart.sh: line 39: /home/ubuntu/macOS-Simple-KVM/tools/dmg2img: cannot execute binary file: Exec format error
```
```
Kernel: 5.11.0-1016-raspi 
Host: Raspberry Pi 4 Model B Rev
```

**Comment by Masamune3210** [comment]
Pretty sure this only supports x86, not arm

**Comment by Cohen-Koen** [comment]
> Pretty sure this only supports x86, not arm

Ok thanks
