### ISSUE TITLE
1920x1080 resolution works with basic.sh but not virt-manager

### ISSUE THREAD

**Issue by geckolinux** [foxlet/macOS-Simple-KVM#51]
Hi, I followed the [instructions](https://passthroughpo.st/new-and-improved-mac-os-tutorial-part-1-the-basics/) to increase the macOS resolution to 1920x1080. When launching the VM with `basic.sh` it works great. But under virt-manager the display is completely corrupted.

![1](https://user-images.githubusercontent.com/2692138/59925082-eab0ae80-93fc-11e9-98c5-21ce272ccccd.png)

I also tried increasing the video RAM as described [here](https://stafwag.github.io/blog/blog/2018/04/22/high-screen-resolution-on-a-kvm-virtual-machine-with-qxl/), but it didn't help.

Any other suggestions to try? Thanks!

**Comment by LukEEEx** [comment]
The same problem

**Comment by mwlczk** [comment]
start the vm with `sudo ./basic.sh` and follow the part "Switching to Virt-Manager" of the same howto you were using. This part is 1-2 scroll pages bellow.

**Comment by geckolinux** [comment]
Do you mean running `./make.sh --add` while the VM is up and running with `sudo ./basic.sh` ?

**Comment by geckolinux** [comment]
OK, I got it working thanks to the tip from @mwlczk . This is the key part:

https://passthroughpo.st/new-and-improved-mac-os-tutorial-part-1-the-basics/
> Boot your VM, and press escape at the first UEFI dialog. Type exit, hit enter. This should bring you to the OVMF configuration menu. Navigate to Device Configuration > OVMF Platform Features, and set the resolution to the same value as your VM resolution.

To be clear, the above part about hitting escape at the first UEFI dialog only works when running the VM from `basic.sh`.

@foxlet Want me to add this to the Docs somewhere?

**Comment by yoolsylva** [comment]
Hi, i got the same problem, but i cannot go to OVMF configuration menu. stuck at here: 
![Screenshot from 2019-08-17 22-33-10](https://user-images.githubusercontent.com/10919797/63214175-1622f180-c13f-11e9-862b-e23e33158e3c.png)
How to go to OVMF configuration menu? Thank very much...

**Comment by EduFrazao** [comment]
@geckolinux dude, how do you enter in the OVMF menu configuration? I hit ESC but nothing happens.

**Comment by sej7278** [comment]
@EduFrazao you press Esc, then type "exit" and press Enter. @geckolinux's instructions don't seem to exactly match the mojave setup (menu names are different) but it works.

Not sure why the other instructions say to just edit config.plist as that simply does not work without editing the ovmf settings.

**Comment by CKingX** [comment]
I managed to do this using virt-manager by adding rEFInd CD Image and having it boot into the firmware settings. This allowed me to change the resolution

**Comment by jameslmoser** [comment]
I was not able to enter the OVMF menu either.  Turns out the problem is having the USB keyboard.  If you remove the USB keyboard, then you can hit ESC and change the resolution.  You have to readd the USB keyboard or you won't be able to use your keyboard with macOS.

**Comment by danipoak** [comment]
> I managed to do this using virt-manager by adding rEFInd CD Image and having it boot into the firmware settings. This allowed me to change the resolution

@CKingX Can you expand on this? I can boot the rEFInd CD image but all I get is a gray screen with the rEFInd logo. Hitting ESC here doesn't do anything. It never progresses beyond this screen either. virt-manager is my only option since launching from basic.sh doesn't work.

**Comment by CKingX** [comment]
The thing here is that rEFInd has a `firmware` option for tools. You can use that to boot into the UEFI setup (which, in this case, opens the same screen as hitting Esc should). That was the thing I tried and it worked. Now, it does require you to include the firmware option so you will need to edit rEFInd configuration: https://rodsbooks.com/refind/configfile.html

**Comment by udf** [comment]
Another option is to boot into the Arch Linux ISO (make sure to boot it as UEFI) and then run `systemctl reboot --firmware-setup` when you get to the shell (I guess any systemd based distro would work for this).

**Comment by TonyKutunio** [comment]
> I was not able to enter the OVMF menu either. Turns out the problem is having the USB keyboard in virt-manager. If you remove the USB keyboard, then you can hit ESC and change the resolution. You have to readd the USB keyboard or you won't be able to use your keyboard with macOS.

What should I do to establish usb connection then?

**Comment by sean9999** [comment]
This did _not_ work for me on Virtual Machine Manager 2.2.1 on Ubuntu 20.10. Is skipped right from Tianocore into Clover as if ESC was not pressed.

> I was not able to enter the OVMF menu either. Turns out the problem is having the USB keyboard in virt-manager. If you remove the USB keyboard, then you can hit ESC and change the resolution. You have to readd the USB keyboard or you won't be able to use your keyboard with macOS.

**Comment by thenaturalwill** [comment]
I found that if i was able to access the OVMF menu editor in Qemu then i could just copy the .ovmf file it creates to be the same name as the one for my qemu install then everything works fine :)

**Comment by ghost** [comment]
Run virtio.sh for a few seconds, then basic.sh, all will be fine
