### ISSUE TITLE
How to use my intel graphics card in vm?

### ISSUE THREAD

**Issue by cathaysia** [foxlet/macOS-Simple-KVM#518]
I using gvt-g created some virtual intel graphics card, and modify vm's xml:

```xml
<hostdev mode="subsystem" type="mdev" managed="no" model="vfio-pci" display="off">
  <source>
    <address uuid="97709d2e-39ff-11ec-bf01-54b203028f37"/>
  </source>
  <alias name="hostdev0"/>
  <address type="pci" domain="0x0000" bus="0x06" slot="0x00" function="0x0"/>
</hostdev>
```

and macos can find this card:

But it not works.

UHD 630 card driver should be in bigSur, how do I use it?

**Comment by notAperson535** [comment]
@cathaysia I do not think you can not use integrated graphics, I think because the host machine needs a graphics card. Sorry if this does not help. I think this person has a similar problem foxlet/macOS-Simple-KVM#510

**Comment by cathaysia** [comment]
Thanks for reply. I am no long using macos in vm. But thanks still.
