### ISSUE TITLE
Screen Glitches QEMU

### ISSUE THREAD

**Issue by 413ph** [foxlet/macOS-Simple-KVM#537]
Hi, I am experiencing some kind of box-like glitches over the screen as shown in the screenshot.
I am running QEMU (basic.sh) on ubuntu host. my iGPU is intel-4600 with a VGA-output monitor. Mojave.
Has anyone fixed this issue? Please let me know, I'd really appreciate it. :D
![Screenshot from 2022-01-23 20-49-46](https://user-images.githubusercontent.com/81858321/150679453-7cfa5805-a0d6-4970-b41e-b904e0da10a9.png)

**Comment by notAperson535** [comment]
@413ph I think safari is just bad without GPU acceleration, which you can not do with iGPUs, mine looked like that too.

**Comment by 413ph** [comment]
Ow that makes sense, thanks mate
