### ISSUE TITLE
Screen Resolution

### ISSUE THREAD

**Issue by usr577** [foxlet/macOS-Simple-KVM#538]
I for some reason can't edit the screen Resolution the folder EFI/Clover just doesn't exist

**Comment by notAperson535** [comment]
you have to mount the efi partition first:


    Open the macOS Terminal and type `diskutil list` and look for the disk/partition location of the EFI. (There may be more than one.)
    Type `sudo diskutil mount diskYsZ`, using the disk/partition location name where you see EFI.
    The EFI partition will appear in the left Finder bar under Volumes.
    If you don't see anything in that volume after browsing to it, try the other ones that you found in `diskutil`.

**Comment by notAperson535** [comment]
@usr577 you have to mount the efi partition first:

Open the macOS Terminal and type `diskutil list` and look for the disk/partition location of the EFI. (There may be more than one.)
    Type `sudo diskutil mount diskYsZ`, using the disk/partition location name where you see EFI.
    The EFI partition will appear in the left Finder bar under Volumes.
    If you don't see anything in that volume after browsing to it, try the other ones that you found in `diskutil`.

**Comment by usr577** [comment]
Thanks for your help it works now

**Comment by notAperson535** [comment]
@usr577 You're welcome. Can you close this then?

**Comment by notAperson535** [comment]
@usr577  You're welcome. Can you close this then?

**Comment by notAperson535** [comment]
> @usr577 you have to mount the efi partition first:
> 
> Open the macOS Terminal and type `diskutil list` and look for the disk/partition location of the EFI. (There may be more than one.) Type `sudo diskutil mount diskYsZ`, using the disk/partition location name where you see EFI. The EFI partition will appear in the left Finder bar under Volumes. If you don't see anything in that volume after browsing to it, try the other ones that you found in `diskutil`.

@usr577 this was in the docs for changing screen resolution
