### ISSUE TITLE
Question regarding virtio.

### ISSUE THREAD

**Issue by SweDennis** [foxlet/macOS-Simple-KVM#541]
Hello, instructions work as stated for basic.sh, but I've been trying to find on what to change in order to use virtio instead of sata, what needs to be changed in virtio.sh and/or basic.sh?

**Comment by notAperson535** [comment]
just run `virtio.sh`

**Comment by notAperson535** [comment]
@SweDennis just run `virtio.sh` instead of `basic.sh`

**Comment by SweDennis** [comment]
Thanks, good to know, I'll look into it some more. What happens is that I don't get the option to install from install media once it starts, only the clover options below. I'll fiddle some more and get back as needed.

**Comment by SweDennis** [comment]
Redid it all, and didn't knowingly change anything, other than increasing the size of my disk from 50G ... either way, works now ...

**Comment by notAperson535** [comment]
@SweDennis Great! Can you close this?

**Comment by SweDennis** [comment]
Of course.
Regards,
/Dennis
