### ISSUE TITLE
Error when starting

### ISSUE THREAD

**Issue by devpranchi** [foxlet/macOS-Simple-KVM#544]
Hi! I don't know what happened, but I successfully installed Mojave on it and I just performed a shutdown. Now here's what happened when I run the script.

```
pranchi@vallessalta:~/macOS-Simple-KVM$ ./basic.sh
qemu-system-x86_64: -drive if=pflash,format=raw,file=/home/pranchi/macOS-Simple-KVM/firmware/OVMF_VARS-1024x768.fd: Could not open '/home/pranchi/macOS-Simple-KVM/firmware/OVMF_VARS-1024x768.fd': No such file or directory```

**Comment by devpranchi** [comment]
Update 1: removing that line on basic.sh fixes it, but I'm not sure yet what's going to happen next.
![image](https://user-images.githubusercontent.com/90830378/155148867-e1349a81-265a-4127-bd81-1c1fd92abfa5.png)

Update 2: now this happened
![image](https://user-images.githubusercontent.com/90830378/155149240-9b323b63-43d3-4081-a6d9-0842ff12cb43.png)

**Comment by notAperson535** [comment]
@devpranchi  go to the firmware directory and tell me what files are in there

**Comment by devpranchi** [comment]
> @devpranchi go to the firmware directory and tell me what files are in there

![image](https://user-images.githubusercontent.com/90830378/155148944-bb3c2e2b-4b59-4eaf-b1bb-5bd773293431.png)

**Comment by devpranchi** [comment]
> @devpranchi go to the firmware directory and tell me what files are in there

![image](https://user-images.githubusercontent.com/90830378/155149045-31f64e6c-a571-4cdd-aa00-f1c61632f4f7.png)

**Comment by notAperson535** [comment]
@devpranchi  add that line you removed back to basic.sh, and run this command in the `firmware` directory
```
wget https://github.com/foxlet/macOS-Simple-KVM/raw/master/firmware/OVMF_VARS-1024x768.fd -O OVMF_VARS-1024x768.fd
```
the command downloads the file that is missing

**Comment by notAperson535** [comment]
@devpranchi so did it work? If so, you can close this issue

**Comment by devpranchi** [comment]
> @devpranchi so did it work? If so, you can close this issue

I guess so, but I still have to check. Will open this once again once it is done. Thanks!

BTW I installed Mojave because Catalina gone stuck on "Estimating time remaining" thing for over 5 hours.

**Comment by notAperson535** [comment]
@devpranchi you can install big sur or Monterey using mine: https://notaperson535.github.io/OneClick-macOS-Simple-KVM/
(Monterey may not work, it seems to work for everyone but me)

**Comment by devpranchi** [comment]
> @devpranchi you can install big sur or Monterey using mine: https://notaperson535.github.io/OneClick-macOS-Simple-KVM/ (Monterey may not work, it seems to work for everyone but me)

Thanks! Will star that repo and take note of that soon.
