### ISSUE TITLE
Stuck at instalation

### ISSUE THREAD

**Issue by echo-saurav** [foxlet/macOS-Simple-KVM#546]
I am stuct here after reboot,
![2022-02-27-003222_1345x796_scrot](https://user-images.githubusercontent.com/76121100/155855013-f5a142d9-dcc6-49b8-9bd6-21c13427244f.png)
 should i close and start or wait?

**Comment by notAperson535** [comment]
@echo-saurav Just wait a while, it usually looks like it gets stuck

**Comment by echo-saurav** [comment]
yes, it was just stuck for forever

**Comment by jabedzaman** [comment]
How it got solved
