### ISSUE TITLE
Suggestion: source for dmg2img

### ISSUE THREAD

**Issue by adrianlshaw** [foxlet/macOS-Simple-KVM#55]
It's not nice that there's a precompiled binary in here. It would great if this repo had either a submodule pointing to the tool dmg2img or a copy of the source itself. It'll also be useful for people who want to tweak this to run on macOS itself (which obviously can't run ELFs natively).

**Comment by deftdawg** [comment]
Wha?

```bash
~/macOS-Simple-KVM$ find . | grep dmg2iso
$
```

**Comment by adrianlshaw** [comment]
Corrected the title to refer to the actual tool name.

**Comment by deftdawg** [comment]
Since the goal of the project is to keep it simple (checking out submodules and spinning up a build chain for a single utility is a bit complex), my suggestion would be rather installing the dependency from the system package manager instead.

```bash
$ apt search dmg2img
Sorting... Done
Full Text Search... Done
dmg2img/bionic 1.6.7-1build1 amd64
  Tool for converting compressed dmg files to hfsplus images
```

**Comment by adrianlshaw** [comment]
Makes sense. We should update the README and remove the precompiled file? I've just checked (with the right name this time) and it's also available in Debian and Homebrew repos.

**Comment by geckolinux** [comment]
Hmmm, what about users of non-Debian/Ubuntu systems? For example, I use openSUSE, and it doesn't have official packages for `dmg2img`.

**Comment by adrianlshaw** [comment]
I had a peek at Fedora's repo and it was present there. Not sure if it's EPEL though.

**Comment by foxlet** [comment]
Not all distros have it available, but I will consider adding a submodule for those who need the source.

**Comment by foxlet** [comment]
The source and submodule have been added, at https://github.com/foxlet/dmg2img
