### ISSUE TITLE
USB keyboard and mouse not working on clover menu

### ISSUE THREAD

**Issue by Bvoxl** [foxlet/macOS-Simple-KVM#550]
After successfully creating the vm, I passed through my spare amd graphics card, as well as my usb mouse and keyboard to the vm through virt-manager. I get a gpu output, however my keyboard and mouse don't function. I have ensured the vm is using usb 2.0 controller. But I am not able to select anything in the clover boot menu. And ideas?

**Comment by notAperson535** [comment]
@Bvoxl The mouse will never work on that menu. You could just wait until it auto-boots the drive. Try removing your AMD GPU and see if that fixes the problem. If that doesn't work, remove and add the usb keyboard to virt-manager

**Comment by Bvoxl** [comment]
@notAperson535 am I required to do anything further than the normal installation, and attachment of the gpu for the display to work? It is just an amd gpu on Catalina. No third-party kexts?

**Comment by notAperson535** [comment]
@Bvoxl I don't think you have to do anything else besides passing through, except maybe install graphics drivers in macOS if needed.
