### ISSUE TITLE
Not cleanly understanding how to make the virtual machine added to virt-manager; virt-manager not allowing the vm to start up

### ISSUE THREAD

**Issue by TamFishe** [foxlet/macOS-Simple-KVM#554]
Hi there, i have this repo for quite some time, but there are some issues that are simply not repairable, even if reading the docs properly. I try to add this virtual machine to virt-manager so i can tweak stuff easily, but seems i quite don't get correctly the instructions on how to properly do it. It seems therefore i do have it in virt-manager, here is an error that i get all the time i want to run the VM:
![image](https://user-images.githubusercontent.com/91405427/161087672-9ef26308-b267-4822-8a60-058769f4e8b6.png)
How can i fix this? Also how can i specify the right path for the VM to be read from? Since i keep more space for on the SSD which is the boot drive for my Linux, i keep this on the hard drive as i don't really need it to be fast and to take precious storage from the main...

**Comment by notAperson535** [comment]
@SallyTheUnknownMan the should be able to just run `./make.sh --add` and it will do it for you. You just have to add the `MyDisk.qcow2` in manually

**Comment by notAperson535** [comment]
Once you do that, run virt-manager as ADMIN using `sudo`

**Comment by TamFishe** [comment]
> Once you do that, run virt-manager as ADMIN using `sudo`
Thanks, that did solve it. Also, seems i did not had the disk added, so thanks for the answer

**Comment by notAperson535** [comment]
@SallyTheUnknownMan you can do these commands so you should not have to use sudo anymore
```
sudo usermod -aG kvm $(whoami)
sudo usermod -aG libvirt $(whoami)
```
