### ISSUE TITLE
failed to connect to the hypervisor

### ISSUE THREAD

**Issue by ghost** [foxlet/macOS-Simple-KVM#558]
when i run the make.sh --add it return an error saying that it was unable to connect to the hypervisor
![image](https://user-images.githubusercontent.com/104024247/164058150-6acf6dd9-be71-44af-9335-e106ca5213cc.png)

**Comment by notAperson535** [comment]
@cohbenobrien try starting the virt-manager service, and run `make.sh` as sudo

**Comment by ghost** [comment]
cheers that worked
