### ISSUE TITLE
Mouse not aligned also changing it to `usb-tablet` not fix the issues on wsl macos 

### ISSUE THREAD

**Issue by ghost** [foxlet/macOS-Simple-KVM#562]
I have changed the script to make mouse aligned but that does not fix the issues.
```
-usb -device usb-kbd -device usb-mouse
```

I have tried this fix but not working. 
```
-usb -device usb-kbd -device usb-tablet
```

How to make mouse cursor aligned?

**Comment by notAperson535** [comment]
@codekryptonian do you mean when you mov the mouse the macos mouse moves to where the mose is slower? Or do you mean that the macOS mouse is not every aligning with the mouse?

**Comment by ghost** [comment]
In clover `usb-tablet` both `usb-mouse` does not work. But it works inside macOS.
The issue is resolved. This is first time I am using macos so when it loads clover mouse does not works. So I didn't boot into macos.
But after `usb-tablet` and proceed to boot into macos using keyboard the mouse works. So, the issue can be closed.

Thanks for your great works!

**Comment by notAperson535** [comment]
@codekryptonian Great! Can this be closed then?

**Comment by ghost** [comment]
Thanks, I am closing it.
