### ISSUE TITLE
gpu passthrough gtx960 on 10.13

### ISSUE THREAD

**Issue by tdfranklinaz** [foxlet/macOS-Simple-KVM#563]
Anyone have luck with a 900 series card on 10.13?

I am getting the following error when booting:
Sleep failure code 0xffffffff 0xffffffff
[ PCI configuration begin ]

and then system just freezes. Tried a bunch of different boot options after doing some googling, but nothing is working for me.

GPU passthrough working, macos just doesn't like the card.

**Comment by notAperson535** [comment]
@tdfranklinaz if it's an Nvidia card, those only work with high sierra or earlier

**Comment by tdfranklinaz** [comment]
@notAperson535 Yes I am running high sierra 10.13.6

**Comment by tdfranklinaz** [comment]
`-vga none \
-device pcie-root-port,bus=pcie.0,multifunction=on,port=1,chassis=1,id=port.1 \
-device vfio-pci,host=02:00.0,bus=port.1,multifunction=on \
-device vfio-pci,host=02:00.1,bus=port.1 \`
    
Both my nvidia 960 and nvidia audio are in the same IOMMU group. I can boot into clover with passthrough but macos gets stuck on PCI config begin. I've tried with clover nvidia web drivers, ive trieed with npci=0x2000 boot argument, and many other boot arguments that people said are useful. 

Really not even sure where to start with this, could it be an issue with the passthrough itself? Should I define the passthrough device differently with qemu? is this a bootloader problem?

**Comment by tdfranklinaz** [comment]
After searching for 16 hours at least, I found this guide and the steps worked perfectly for me:
https://null-src.com/posts/qemu-vfio-pci/post.php

**Comment by notAperson535** [comment]
@tdfranklinaz Great!
