### ISSUE TITLE
qxl_send_events: spice-server bug: guest stopped, ignoring

### ISSUE THREAD

**Issue by NatanielRegula** [foxlet/macOS-Simple-KVM#570]
Hi, when I run `./basic.sh` this is the output I get 
`qxl_send_events: spice-server bug: guest stopped, ignoring
VNC server running on ::1:5900`

I tried to find a solution by searching the error but I couldn't find any meaningful help.

**Comment by notAperson535** [comment]
@NatanielRegula see here: https://github.com/notAperson535/OneClick-macOS-Simple-KVM/issues/17#issuecomment-1138772224

**Comment by NatanielRegula** [comment]
@notAperson535 Thanks a lot. Closing.
