### ISSUE TITLE
Not booting

### ISSUE THREAD

**Issue by Abzl0** [foxlet/macOS-Simple-KVM#577]
i have followed al the steps and i'm getting this unusual error

![PXL_20220824_084748753](https://user-images.githubusercontent.com/111192208/186424740-3fabedac-e34d-44b0-af01-10fad431f175.jpg)
I'm guessing it maybe something to do with my cpu's compatibility

**Comment by notAperson535** [comment]
@Abzl0 download vnc viewer or another vnc service and connect to `localhost:5900`

**Comment by ghost** [comment]
Did you make sure you installed the full QEMU version? Install the `qemu-full` package and try again
