### ISSUE TITLE
Sane default RAM should be 4G otherwise kernel error

### ISSUE THREAD

**Issue by kragil** [foxlet/macOS-Simple-KVM#58]
I love this, but I had to edit the bash.sh and increase the RAM size to 4G otherwise the installed system would not boot and quit immediately with a kernel error.

**Comment by deftdawg** [comment]
It boot fine for me with the default, think it's 2GB by default.

**Comment by geckolinux** [comment]
Works fine for me with 2GB also.

**Comment by norcalli** [comment]
Running High Sierra with 2GB ram works fine for me as well. @kragil you should add more information to this report so that the discrepancy could be explained.

**Comment by kragil** [comment]
Hello again. I installed Mojave on a Ryzen 2400g system on Ubuntu 19.10 with wayland and kernel 5.1.14. I used the defaults and I think I got an error in a phyton process. I will try again with 2GB and report back once I am at my Linux box again.

**Comment by foxlet** [comment]
There might be an issue with KASLR mapping in the current implementation, so I'll be checking on that.

**Comment by tomchiverton** [comment]
I had to adjust to 4G as well, or when the machine reboots from the installer to boot off the disk image it crashes.

Intel i7-6700 on Ubuntu 18.04 LTS

**Comment by foxlet** [comment]
Please check again for any issues booting below 4G of memory.
