### ISSUE TITLE
Mouse doesn't sync with VM

### ISSUE THREAD

**Issue by EndCod3r** [foxlet/macOS-Simple-KVM#588]
I'm on Windows 11 using WSL(g/2) to use QEMU and everything installed fine and is working except the mouse. The cursor doesn't sync up to where I moving my cursor, is there a way to fix this?
![msrdc_2nMRJj4Qbt](https://user-images.githubusercontent.com/73094718/206812255-cbc5a72f-885a-4fcb-9713-ee94c3be29d3.png)

**Comment by notAperson535** [comment]
@Endlord15 try changing the this line in basic.sh
```
-usb -device usb-kbd -device usb-mouse \
```

to 

```
-usb -device usb-kbd -device usb-tablet \
```

**Comment by EndCod3r** [comment]
This works perfectly, thank you for the support!
