### ISSUE TITLE
Getting this to work on Azure

### ISSUE THREAD

**Issue by grav** [foxlet/macOS-Simple-KVM#59]
The FAQ states that this project should work with Azure. I tried briefly to setup a VM, but failed on some permission issue.

It would be awesome with a guide that dictates exactly how to set everything up, eg:
1. what image to use (Ubuntu 18, ...)
2. what size of vm to use (as far as I understand, only newer generations are able to run a VM inside a VM)
3. what packages to install, how to get vnc working, etc etc
4. describe the limitations of running in Azure (sound not working? no gfx accel?)

Since the environment is exactly the same for everyone, it should be entirely possible to make a step-by-step guide that nails it :-)

**Comment by foxlet** [comment]
I don't have access to Azure, but I can take a look in a bit (assuming they have open access).

**Comment by grav** [comment]
They do have a free trial where you can run a VM such as "Standard E4 v3 (4 vcpus, 32 GiB memory " for around a month.

**Comment by foxlet** [comment]
![Azure test.](https://i.imgur.com/sehE2kW.jpg)

**Comment by foxlet** [comment]
The test machine was a `Standard D2s v3 (2 vcpus, 8 GiB memory)` configuration with `Ubuntu 18.04 LTS`.

You will need to allow port 22 (SSH) and 5900 (VNC) in your NSG.

The default Azure image doesn't give permissions for the `kvm` group, so when connecting via SSH, first run:
```
sudo usermod -a -G kvm $USER
```
Disconnect (log off) and connect again to allow group changes to take place.

The rest is verbatim from the main documentation.
```
git clone https://github.com/foxlet/macOS-Simple-KVM.git
sudo apt-get update
sudo apt-get install qemu-system qemu-utils python3 python3-pip
cd macOS-Simple-KVM
./jumpstart.sh --mojave
qemu-img create -f qcow2 MyDisk.qcow2
MEM=7G CPUS=2 SYSTEM_DISK=MyDisk.qcow2 HEADLESS=1 ./headless.sh
```

**Comment by foxlet** [comment]
Something like Azure is probably better geared for command-line, Xcode, and CI/Build applications.

The limitations for any cloud system will be pretty similar. macOS depends on particular graphics cards (AMD mostly), so the display will be limited to software rendering (which is better in Mojave than High Sierra). 

The default headless setup doesn't support any sound, and although libvirt could technically enable it (with latency), alternatives like JACK are much better in terms of remote sound.

**Comment by grav** [comment]
Thanks a lot @foxlet - `usermod` together with the `headless.sh` env vars got me going. The only caveat was that I had to create the `kvm` group first.

Also, good point regarding software rendering and Mojave, didn't know that. 

The request is solved for me, so I'll close the issue.
