### ISSUE TITLE
Gets stuck at imageboot_setup_new: successfully authenticated /macOS Install/BaseSystem.dmg

### ISSUE THREAD

**Issue by EndCod3r** [foxlet/macOS-Simple-KVM#590]
Like I said the KVM gets stuck on imageboot_setup_new: successfully authenticated /macOS Install Data/BaseSystem.dmg

I'm on Windows 11 using WSL2 and macOS version is Catalina

**Comment by notAperson535** [comment]
@Endlord15 Try using my repo: https://oneclick-macos-simple-kvm.notaperson535.is-a.dev/

It has a dedicated windows install guide, and you  can install new os', and it may solve your problem.

**Comment by EndCod3r** [comment]
> @Endlord15 Try using my repo: https://oneclick-macos-simple-kvm.notaperson535.is-a.dev/
> 
> It has a dedicated windows install guide, and you can install new os', and it may solve your problem.

@notAperson535 I'm followed the docs on the repo everything was working fine except at the end when running ./setup.sh. After sometime of downloading the BaseSystem.dmg file the download freezes and I left it on for about 3 hours and it didn't change. I've tried restarting the setup.sh and deleting BaseSystem.dmg but I got nothing to work.
