### ISSUE TITLE
Disk Utility reports wrong disk size

### ISSUE THREAD

**Issue by IzKuipers** [foxlet/macOS-Simple-KVM#595]
Hi all,

I decided to finally try out this project as the concept behind it seemed like a really good idea. And it is! I even got it running under WSL2. I do however have one major issue that prevents me from using it entirely.

On the main README.md file in the root of this project, the command listed to create the virtual harddisk,
```bash
qemu-img create -f qcow2 MyDisk.qcow2 64G
```
creates a 64GB drive, sure, even according to Qemu itself. But, macOS shows a disk size of 163.9MB:
![MacOS shows 163.9MB](https://user-images.githubusercontent.com/76709090/212563693-13ff8f72-ce32-43c9-b1e2-3968cc734c0e.png)
while `qemu-img info MyDisk.qcow2` shows the correct 64GB of capacity:
![image](https://user-images.githubusercontent.com/76709090/212563727-644a329a-f8a3-4f99-bda7-1ded53df8fdb.png)

I haven't found any solution to this problem.

It happens on every system I try it on, from Linux Mint 21 Cinnamon to WSL 2 on Windows 11 22621.1105.

Does anyone know how to fix this issue?

**Comment by digitalkram** [comment]
Actually this is the second partition of disk 0 (as indicated by the trailing ``2``).

First use DiskUtility to format/initialize the first partition and afterwards it is selectable in the installer.

**Comment by IzKuipers** [comment]
It appears I put the the arguments for assigning the disk to the KVM in the wrong place, I added it to the end of the basic.sh commandline instead of _in_ the basic.sh, my bad.

Maybe someone could update the instructions a bit to make it just a tad clearer.
