### ISSUE TITLE
l

### ISSUE THREAD

**Issue by Ambrosia0x00** [foxlet/macOS-Simple-KVM#608]
![Screenshot_1](https://github.com/foxlet/macOS-Simple-KVM/assets/81118832/140ad738-3db4-4744-9b85-37db080393f0)
anyone know what i did wrong?

**Comment by Masamune3210** [comment]
thunderbird absolutely LOVES your name btw lol
![image](https://github.com/foxlet/macOS-Simple-KVM/assets/1053504/f76b61c0-54e3-4997-875c-12fb94f27d14)
