### ISSUE TITLE
newbie question: Broadcom?

### ISSUE THREAD

**Issue by mrose17** [foxlet/macOS-Simple-KVM#61]
let's say i wanted to use a RPi 4 (Broadcom BCM2711, Quad core Cortex-A72 (ARM v8) 64-bit SoC @ 1.5GHz)  is that a no-go? sorry for the lack of clue.

**Comment by deftdawg** [comment]
OSX only runs on x86-64, doesn't run on Arm, so no-go.

**Comment by mrose17** [comment]
thanks... just checking...

**Comment by foxlet** [comment]
Software mode would probably be pretty slow, I haven't tested it so I can't say much about full-CPU emulation.
