### ISSUE TITLE
Error starting domain: Cannot access storage file '/home/tarif/macOS-Simple-KVM/ESP.qcow2' (as uid:64055, gid:109): Permission denied

### ISSUE THREAD

**Issue by tarifalhasan** [foxlet/macOS-Simple-KVM#620]
Error starting domain: Cannot access storage file '/home/tarif/macOS-Simple-KVM/ESP.qcow2' (as uid:64055, gid:109): Permission denied

Traceback (most recent call last):
  File "/usr/share/virt-manager/virtManager/asyncjob.py", line 72, in cb_wrapper
    callback(asyncjob, *args, **kwargs)
  File "/usr/share/virt-manager/virtManager/asyncjob.py", line 108, in tmpcb
    callback(*args, **kwargs)
  File "/usr/share/virt-manager/virtManager/object/libvirtobject.py", line 57, in newfn
    ret = fn(self, *args, **kwargs)
  File "/usr/share/virt-manager/virtManager/object/domain.py", line 1384, in startup
    self._backend.create()
  File "/usr/lib/python3/dist-packages/libvirt.py", line 1353, in create
    raise libvirtError('virDomainCreate() failed')
libvirt.libvirtError: Cannot access storage file '/home/tarif/macOS-Simple-KVM/ESP.qcow2' (as uid:64055, gid:109): Permission denied

**Comment by Masamune3210** [comment]
It's telling you what the issue is right in the message you copies. The user in question does not have permission to open the file.

**Comment by tarifalhasan** [comment]
> It's telling you what the issue is right in the message you copies. The user in question does not have permission to open the file.

when i try to run os on vm   
![Screenshot from 2023-11-08 23-27-25](https://github.com/foxlet/macOS-Simple-KVM/assets/92237522/cd6b6bb3-ded1-45af-b202-f952842176eb)

**Comment by Masamune3210** [comment]
I already told you the same thing the message you posted originally and this one are both also telling you. The user account does not have permission to access the file.

**Comment by tarifalhasan** [comment]
> I already told you the same thing the message you posted originally and this one are both also telling you. The user account does not have permission to access the file.

How i can access permission?

**Comment by fybedev** [comment]
> > I already told you the same thing the message you posted originally and this one are both also telling you. The user account does not have permission to access the file.
> 
> How i can access permission?

Chown or chmod
