### ISSUE TITLE
spam in dmesg

### ISSUE THREAD

**Issue by sinetek** [foxlet/macOS-Simple-KVM#63]
this project is great but i'm getting a lot of spam in dmesg. could we fix this?

**Comment by sinetek** [comment]
using 10.15

**Comment by deftdawg** [comment]
Well it would help to know what kind of message is getting spammed and if you're referring to dmesg on the Linux host or the OSX VM...

**Comment by sinetek** [comment]
![image](https://user-images.githubusercontent.com/5908875/60378010-82755480-9a1c-11e9-930a-2f16be33aa68.png)

**Comment by foxlet** [comment]
We don't have control of debug output in beta builds.

**Comment by sinetek** [comment]
ah ok that makes sense. closing
