### ISSUE TITLE
How to increase screen resolution when used with Virt-Manager?

### ISSUE THREAD

**Issue by JulianChia** [foxlet/macOS-Simple-KVM#630]
I have completed Step 2a of README.md without any problem:

```
## Step 2a (Virtual Machine Manager)
1. If instead of QEMU, you'd like to import the setup into Virt-Manager for further configuration, just run `sudo ./make.sh --add`.
2. After running the above command, add `MyDisk.qcow2` as storage in the properties of the newly added entry for VM.
```

I encountered a big problem after changing the screen resolution per your [instruction](https://github.com/foxlet/macOS-Simple-KVM/blob/master/docs/guide-screen-resolution.md). Pressing the `Esc` key during Reboot is not recognised when using `Virt-Manager`, hence Step 2 on `How to increase screen resolution for macOS-Simple-KVM` can't be done in `Virt-Manager` although it works for `QEMU`.

```
2. Shut down the VM, relaunch it using `basic.sh` script and follow the following steps:
 - Press `Escape` key as soon as the window comes up.
 - In the interface that comes up, select `Device Manager`->`OVMF Platform Configuration`->`Change Preferred` and select the correct resolution.
 - Press `F10` to save the changes.
 - Press `Escape` multiple times to come back to main menu, and then select `Continue` on it.
```

Consequently, my screen becomes unusable like so:

![Virt-Manager_after_resolution_inreased](https://github.com/foxlet/macOS-Simple-KVM/assets/61495791/8a351ebb-7e6c-4a27-8fd8-3f839a480854)

How do I increase the VM resolution without breaking the VM? 

I am using Ubuntu 22.04 and  Virtual Machine Manager 4.0.0. I had increased the resolution to 1920x1080.

**Comment by JulianChia** [comment]
Fixed. Closing this issue. 

![Virt-Manager_after_resolution_inreased-fixed](https://github.com/foxlet/macOS-Simple-KVM/assets/61495791/099635b3-8c89-4cbd-be0f-686840a3e940)

**Comment by tone-milazzo** [comment]
What was the fix please?

**Comment by otuva** [comment]
@tone-milazzo 

You have to follow all the steps basically. If you update the config.plist you then have to update OVMF Platform Configuration and vice versa.

https://github.com/foxlet/macOS-Simple-KVM/blob/master/docs/guide-screen-resolution.md
