### ISSUE TITLE
How to install driver for GTX 750 with mojave?

### ISSUE THREAD

**Issue by lihk11** [foxlet/macOS-Simple-KVM#65]

**Comment by darkyelox** [comment]
If you want to use GPU acceleration you need to vfio for passthrough but this means you must to have another GPU in your desktop because one GPU is for your host system and the other for your KVM MacOS machine

**Comment by foxlet** [comment]
If the card doesn't work out of the box, it will generally not work. You need a Kepler card to use Mojave, and the GTX 750 is based on Maxwell, which is unsupported.
