### ISSUE TITLE
qemu rebooting during install

### ISSUE THREAD

**Issue by Thesicstar** [foxlet/macOS-Simple-KVM#66]
I set up everything according to the readme, qemu starts, clover is showing, but as soon as i try and run the installer, at some certain point the qemu reboots
I'm trying to install Mojave, tried it with graphics and without (vnc).
Installing High Sierra gives me a kernel error.

is there a way to log whats going on inside of qemu?

I'm kinda new to this so i don't really know what to do now..
![Peek 2019-07-04 23-01](https://user-images.githubusercontent.com/37235804/60688406-28a9da00-9eb5-11e9-8996-a11ebbdf4039.gif)

**Comment by foxlet** [comment]
That's an SMC read error, generally due to old QEMU versions being used. Did you check the minimum requirements?

**Comment by Thesicstar** [comment]
Ah! I see, the default qemu package for debian stretch is still qemu 2.8, gotta install 3.1 manually.
Thanks so much!
