### ISSUE TITLE
Precisions needed about laptop dGPU

### ISSUE THREAD

**Issue by MeisterTea** [foxlet/macOS-Simple-KVM#70]
Hi, I have gpu passthrough with bumblebee working thank's to this guide https://gist.github.com/Misairu-G/616f7b2756c488148b7309addc940b28

The gpu is recognized and I have nvidia web drivers working.
My question is: Is it possible to have the display in qemu window ?
When I set ```-vga none```, the only thing I get is the qemu prompt window.

Is there a way to get the vm working on the laptop screen ?

**Comment by deftdawg** [comment]
If you pass through a video card, you're only going to get acceleration on displays physically connected to it I believe.   So for an egpu, the ports on the back of the egpu.

**Comment by foxlet** [comment]
No, for discrete GPUs you either need a separate display attached (so anything on the external display ports) or disable X11 and allow macOS to control the primary display. You cannot use it in a window.
