### ISSUE TITLE
Guest machines not active after a while idle.

### ISSUE THREAD

**Issue by Julioevm** [foxlet/macOS-Simple-KVM#72]
So, I've set up 3 laptops to run these virtual machines, everything seems to work fine, I have them running a selenium server each to run some tests on safari. But after they have been idle for a while it seems like they stop responding, and I'm not sure if it's the VM or the Host causing this.

I have them with bridged connections, so each vm has its own IP. 
I have disabled all the mac os energy saving options and screen saver, also enable automatic login so the session doesn't close. 
If I get to the host and interact with the vm it looks like the screen of the vm has frozen until I send some input, like moving the mouse, but Im not sure if this is just mac os disabling the display for energy saving. 

Any ideas about this? Could KVM cause this? Should I look further into mac os itself or could the host be the culprit?, its Ubuntu 18.10.
I have some mac os machines running on vmware which I replicated the macos configuration and they dont seem to have this issue.

Any help is appreciated, thanks!

**Comment by deftdawg** [comment]
I'm on Ubuntu 18.04 (KDE Neon), my qemu is pretty ancient (2.11).  What I observe, is if I let the VM idle for a long period of time and then go into it, nothing on the screen will repaint until I release the machine (left ctrl+alt), at which point the screen will repaint with the lock screen dialog and if I recapture input, I can unlock and use normally.

I'm on Mojave for the guest, I suspect it's my old qemu (maybe how qxml GFX driver handles screen saver or dpms sleep or something), but I'd be interested to hear from others with much newer qemu versions.

**Comment by foxlet** [comment]
You need to disable display sleep in Energy Saver.

**Comment by Julioevm** [comment]
That was it thanks!
