### ISSUE TITLE
can't fetch Catalania

### ISSUE THREAD

**Issue by pi2in3** [foxlet/macOS-Simple-KVM#78]
i want Catalania but mojave downloaded every time :
[ho3in@fedoraGnome macOS-Simple-KVM-master]$ ./jumpstart.sh --catalina
Requirement already satisfied: requests in /usr/lib/python3.7/site-packages (from -r requirements.txt (line 1)) (2.21.0)
Requirement already satisfied: click in /home/ho3in/.local/lib/python3.7/site-packages (from -r requirements.txt (line 2)) (7.0)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/lib/python3.7/site-packages (from requests->-r requirements.txt (line 1)) (3.0.4)
Requirement already satisfied: idna<2.9,>=2.5 in /usr/lib/python3.7/site-packages (from requests->-r requirements.txt (line 1)) (2.7)
Requirement already satisfied: urllib3<1.25,>=1.21.1 in /usr/lib/python3.7/site-packages (from requests->-r requirements.txt (line 1)) (1.24.3)
2019-07-22 18:09:25,745 Network Request: Fetching https://swscan.apple.com/content/catalogs/others/index-10.15seed-10.15-10.14-10.13-10.12-10.11-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog
2019-07-22 18:09:35,531 Selected macOS Product: 041-88929
Fetching BaseSystem/BaseSystem.dmg ... [####################################] 100%

**Comment by hactiv8** [comment]
I’m having the same problem can’t seem to find a solution on this

**Comment by freeubi** [comment]
There is a fix here: https://github.com/foxlet/macOS-Simple-KVM/issues/75

**Comment by freeubi** [comment]
It was tricky, but I could install Catalina too.
Unfortunately, the fix mentioned above doesnt worked reliably - it was ok for the first time, but I couldn't make it after that. 
- From the BaseImage, I got the redownload loop issue.
- From the pre-downloaded version (not easy to get that image) i could start the installer, but I got corrupted installer error on the end.

My current, working solution is:
- first, install a Mojave (its working (for me at least) with the full downloader method)
- then try to update your system.

**Comment by jacksonchui** [comment]
@freeubi your method worked for me. You have to install Mojave first and then use the System Updater and a beta profile to update to Catalina. I too tried with a downloaded installer and it just threw a kernel panic and rebooted.

**Comment by sej7278** [comment]
i'm having the same problem - i keep getting the mojave installer despite the jumpstart.sh logs saying:

```
2019-09-27 00:12:28,718 Network Request: Fetching https://swscan.apple.com/content/catalogs/others/index-10.15seed-10.15-10.14-10.13-10.12-10.11-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog
2019-09-27 00:12:31,768 Selected macOS Product: 061-21551
```
