### ISSUE TITLE
increase vram...

### ISSUE THREAD

**Issue by chengjk84** [foxlet/macOS-Simple-KVM#79]
I hv set qxl vram to 512MB... how can i increase mojave vram? do i need to editing something to make it work?

**Comment by foxlet** [comment]
Software graphics like QXL operate with a framebuffer, they don't rely on any more VRAM than given. If you want accelerated graphics you'll need to pass a graphics card.

**Comment by chengjk84** [comment]
i just need to make it as 128MB like i can in vmware... any idea how???

**Comment by foxlet** [comment]
You can try `-std vga`, but this isn't VMware, don't expect it to function in the same way.

**Comment by jsjb** [comment]
You might try adding a line containing `-global qxl-vga.vram_size_mb=128 -global qxl-vga.ram_size_mb=128 \` to `basic.sh`.

Foxlet, QXL can still allocate host system RAM (but not host VRAM, I believe) to the emulated graphics device as VRAM so the guest OS can store large textures or whatever; see [hw/display/qxl.c](https://github.com/qemu/qemu/blob/master/hw/display/qxl.c) in the QEMU source. This flag is commonly used by people rendering 4K displays on software graphics, bless their poor souls :p

**Comment by foxlet** [comment]
Yes, but again, none of that applies because macOS does not have a QXL driver, it treats it like a dummy framebuffer.
