### ISSUE TITLE
Is it possible to run without KVM?

### ISSUE THREAD

**Issue by rcrowe-google** [foxlet/macOS-Simple-KVM#80]
I have an interesting challenge.  I can't load KVM on my system, because I'm not allowed to.  So I know it will be slow, if I can get it to work.  I can almost get QEMU to run by modifying the basic.sh script, but it doesn't quite start.  See attached screenshot.

![qemu-start-072919](https://user-images.githubusercontent.com/44788059/62089143-b3fc5e00-b21c-11e9-96c5-66d62c09dfe3.png)

I get an error:
> warning: TCG doesn't support requested feature: CPUID.01H:ECX.vmx [bit 5]

Here's my modified basic.sh:

```
#!/bin/bash

OSK="ourhardworkbythesewordsguardedpleasedontsteal(c)AppleComputerInc"
VMDIR=$PWD
OVMF=$VMDIR/firmware
#export QEMU_AUDIO_DRV=pa
#QEMU_AUDIO_DRV=pa

qemu-system-x86_64 \
    -m 2G \
    -device isa-applesmc,osk="$OSK" \
    -smbios type=2 \
    -drive if=pflash,format=raw,readonly,file=$OVMF/OVMF_CODE.fd \
    -drive if=pflash,format=raw,file=$OVMF/OVMF_VARS-1024x768.fd \
    -vga qxl \
    -device ich9-intel-hda -device hda-output \
    -usb -device usb-kbd -device usb-mouse \
    -netdev user,id=net0 \
    -device e1000-82545em,netdev=net0,id=net0,mac=52:54:00:c9:18:27 \
    -device ich9-ahci,id=sata \
    -drive id=ESP,if=none,format=qcow2,file=ESP.qcow2 \
    -device ide-hd,bus=sata.2,drive=ESP \
    -drive id=InstallMedia,format=raw,if=none,file=BaseSystem.img \
    -device ide-hd,bus=sata.3,drive=InstallMedia \
    -drive id=SystemDisk,if=none,file=MyDisk.qcow2 \
    -device ide-hd,bus=sata.4,drive=SystemDisk \

```
One other question - the instructions say:
> Remember to partition in Disk Utility first!

but I have no idea what that means.  I mean, I know what disk partitioning is, but what is this `Disk Utility` and where do I find it?  Is that the reason I'm having problems?

**Comment by videah** [comment]
>but I have no idea what that means. I mean, I know what disk partitioning is, but what is this Disk Utility and where do I find it? Is that the reason I'm having problems?

![image](https://user-images.githubusercontent.com/4761786/62166221-200fbc80-b318-11e9-9983-57b98fc86cc9.png)

It's a tool included in the installer.

**Comment by foxlet** [comment]
You need to keep the  config, otherwise the QEMU CPUID data will be used which crashes XNU.

**Comment by foxlet** [comment]
This is a draft TCG config, it's enough to start XNU but crashes due to incomplete instructions (AES is broken in TCG).

```
#!/bin/bash

OSK="ourhardworkbythesewordsguardedpleasedontsteal(c)AppleComputerInc"
VMDIR=$PWD
OVMF=$VMDIR/firmware
#export QEMU_AUDIO_DRV=pa
#QEMU_AUDIO_DRV=pa

qemu-system-x86_64 \
    -no-kvm \
    -m 2G \
    -machine q35 \
    -smp 4,cores=2 \
    -cpu Penryn,vendor=GenuineIntel,+sse3,+sse4.2,+xsave,+avx,+xsaveopt,+xsavec,+xgetbv1,+avx2,+bmi2,+smep,+bmi1,+fma,+movbe,+invtsc \
    -device isa-applesmc,osk="$OSK" \
    -smbios type=2 \
    -drive if=pflash,format=raw,readonly,file=$OVMF/OVMF_CODE.fd \
    -drive if=pflash,format=raw,file=$OVMF/OVMF_VARS-1024x768.fd \
    -vga qxl \
    -device ich9-intel-hda -device hda-output \
    -usb -device usb-kbd -device usb-mouse \
    -netdev user,id=net0 \
    -device e1000-82545em,netdev=net0,id=net0,mac=52:54:00:c9:18:27 \
    -device ich9-ahci,id=sata \
```

**Comment by rcrowe-google** [comment]
@videah Thanks, I wasn't seeing that because I wasn't getting that far!

@foxlet Wow, thanks for the TCG config!  If I'm reading this right though, until/if AES is fixed in TCG this config will crash, right?  Who owns TCG?

**Comment by foxlet** [comment]
TCG is an internal project, part of QEMU, so they manage it alongside backends for KVM. https://git.qemu.org/?p=qemu.git;a=blob_plain;f=tcg/README;hb=HEAD has a README.

**Comment by rcrowe-google** [comment]
Is this the bug?
https://bugs.launchpad.net/qemu/+bug/1813201

**Comment by foxlet** [comment]
I haven’t debugged the exact issue in detail, but the crashes are later in boot (during kext startup), the core kernel is more or less fine.
