### ISSUE TITLE
Kernel Panic with AMD Radeon HD 7870 on Ryzen

### ISSUE THREAD

**Issue by modzilla99** [foxlet/macOS-Simple-KVM#81]
Hey guys,

I always get a kernel panic when booting the hackintosh vm with my GPU! Did I do sth wrong?

> *** Panic Report ***
> 
> panic(cpu 1 caller 0xffffff80096daadd): Kernel trap at 0xffffff7f8bf74b0a, type 14=page fault, registers:
> 
> CR0: 0x000000008001003b, CR2: 0xffffff811599c000, CR3: 0x000000000c731000, CR4: 0x00000000000406e0
> 
> RAX: 0xffffff811599c000, RBX: 0x0000000000005434, RCX: 0x0000000002000000, RDX: 0x0000000003000000
> 
> RSP: 0xffffff8112bcbbe0, RBP: 0xffffff8112bcbc00, RSI: 0xffffff801f4cf490, RDI: 0x0000000000000000
> 
> R8: 0x0000000000000002, R9: 0x0000000000000003, R10: 0x0000000080000000, R11: 0xffffff7f89eb53b8
> 
> R12: 0xffffff801baa7d40, R13: 0xffffff80d9e8f000, R14: 0x0000000000000000, R15: 0xffffff801ad6b8c0
> 
> RFL: 0x0000000000010246, RIP: 0xffffff7f8bf74b0a, CS: 0x0000000000000008, SS: 0x0000000000000010
> 
> Fault CR2: 0xffffff811599c000, Error code: 0x0000000000000002, Fault CPU: 0x1 VMM, PL: 0, VF: 1
> 
> 
> Backtrace (CPU 1), Frame : Return Address
> 
> 0xffffff8112bcb6b0 : 0xffffff80095ad6ed
> 
> 0xffffff8112bcb700 : 0xffffff80096e9185
> 
> 0xffffff8112bcb740 : 0xffffff80096da8ba
> 
> 0xffffff8112bcb7b0 : 0xffffff800955ab40
> 
> 0xffffff8112bcb7d0 : 0xffffff80095ad107
> 
> 0xffffff8112bcb8f0 : 0xffffff80095acf53
> 
> 0xffffff8112bcb960 : 0xffffff80096daadd
> 
> 0xffffff8112bcbad0 : 0xffffff800955ab40
> 
> 0xffffff8112bcbaf0 : 0xffffff7f8bf74b0a
> 
> 0xffffff8112bcbc00 : 0xffffff7f8bf84047
> 
> 0xffffff8112bcbc20 : 0xffffff7f8bf749f4
> 
> 0xffffff8112bcbc60 : 0xffffff7f8bf950df
> 
> 0xffffff8112bcbcb0 : 0xffffff7f8bf83e18
> 
> 0xffffff8112bcbcd0 : 0xffffff7f8bf1b80c
> 
> 0xffffff8112bcbd20 : 0xffffff7f8bf197f6
> 
> 0xffffff8112bcbd60 : 0xffffff7f8be9f8e8
> 
> 0xffffff8112bcbde0 : 0xffffff7f8bf17e3e
> 
> 0xffffff8112bcbe40 : 0xffffff8009c2ed7b
> 
> 0xffffff8112bcbe80 : 0xffffff8009c2ea35
> 
> 0xffffff8112bcbf00 : 0xffffff8009c2dff7
> 
> 0xffffff8112bcbf50 : 0xffffff8009c2fae6
> 
> 0xffffff8112bcbfa0 : 0xffffff800955a0ce
> 
> Kernel Extensions in backtrace:
> 
> com.apple.iokit.IOAcceleratorFamily2(404.14)[618B24B5-1387-31FD-A7F7-53283E2C3FEA]@0xffffff7f8be71000->0xffffff7f8bf16fff
> 
> dependency: com.apple.driver.AppleMobileFileIntegrity(1.0.5)[888F591F-8A21-30F9-812F-D366292AA679]@0xffffff7f8a322000
> 
> dependency: com.apple.iokit.IOSurface(255.6.1)[263BDC28-38C8-3995-BB6B-AD419E41C2DC]@0xffffff7f8bd15000
> 
> dependency: com.apple.iokit.IOPCIFamily(2.9)[202F4F5C-5E3C-35A9-A7AD-F85B0E3CD199]@0xffffff7f89e95000
> 
> dependency: com.apple.iokit.IOGraphicsFamily(530.66)[373EAB85-2C5F-3B84-B86D-421F79C47DF2]@0xffffff7f8b975000
> 
> dependency: com.apple.iokit.IOReportFamily(47)[0BC9F93B-456A-3D97-BE4C-69DCBB5E8A3C]@0xffffff7f8a8c0000
> 
> com.apple.kext.AMDRadeonX4000(2.1.1)[8196EE21-7C89-3CF1-A619-701FB1604217]@0xffffff7f8bf17000->0xffffff7f8c356fff
> 
> dependency: com.apple.iokit.IOSurface(255.6.1)[263BDC28-38C8-3995-BB6B-AD419E41C2DC]@0xffffff7f8bd15000
> 
> dependency: com.apple.iokit.IOPCIFamily(2.9)[202F4F5C-5E3C-35A9-A7AD-F85B0E3CD199]@0xffffff7f89e95000
> 
> dependency: com.apple.iokit.IOGraphicsFamily(530.66)[373EAB85-2C5F-3B84-B86D-421F79C47DF2]@0xffffff7f8b975000
> 
> dependency: com.apple.iokit.IOAcceleratorFamily2(404.14)[618B24B5-1387-31FD-A7F7-53283E2C3FEA]@0xffffff7f8be71000
> 
> 
> BSD process name corresponding to current thread: kernel_task
> 
> Boot args: -v
> 
> 
> Mac OS version:
> 
> 18G87
> 
> 
> Kernel version:
> 
> Darwin Kernel Version 18.7.0: Thu Jun 20 18:42:21 PDT 2019; root:xnu-4903.270.47~4/RELEASE_X86_64
> 
> Kernel UUID: 982F17B3-0252-37FB-9869-88B3B1C77335
> 
> Kernel slide: 0x0000000009200000
> 
> Kernel text base: 0xffffff8009400000
> 
> __HIB text base: 0xffffff8009300000
> 
> System model name: iMac10,1 (Mac-F2268CC8)
> 
> 
> System uptime in nanoseconds: 43539098623
> 
> last loaded kext at 43443099134: com.apple.kext.AMDRadeonX4030HWLibs 1.0 (addr 0xffffff7f8c357000, size 7655424)
> 
> loaded kexts:
> 
> as.vit9696.WhateverGreen 1.3.0
> 
> as.vit9696.Lilu 1.3.7
> 
> com.apple.kext.AMDRadeonX4000 2.1.1
> 
> com.apple.driver.AppleGraphicsDevicePolicy 3.50.12
> 
> com.apple.AGDCPluginDisplayMetrics 3.50.12
> 
> com.apple.driver.AppleHV 1
> 
> com.apple.iokit.IOUserEthernet 1.0.1
> 
> com.apple.iokit.IOBluetoothSerialManager 6.0.14d3
> 
> com.apple.driver.pmtelemetry 1
> 
> com.apple.driver.AGPM 110.25.11
> 
> com.apple.Dont_Steal_Mac_OS_X 7.0.0
> 
> com.apple.driver.AppleQEMUHID 2.1.3
> 
> com.apple.driver.AppleVmxnet3Ethernet 1.0.8
> 
> com.apple.kext.AMD7000Controller 2.1.1
> 
> com.apple.driver.AppleFIVRDriver 4.1.0
> 
> com.apple.driver.AppleOSXWatchdog 1
> 
> com.apple.driver.ACPI_SMC_PlatformPlugin 1.0.0
> 
> com.apple.driver.AppleIntelSlowAdaptiveClocking 4.0.0
> 
> com.apple.fileutil 20.036.15
> 
> com.apple.filesystems.autofs 3.0
> 
> com.apple.driver.AppleFileSystemDriver 3.0.1
> 
> com.apple.filesystems.apfs 945.275.7
> 
> com.apple.filesystems.hfs.kext 407.200.4
> 
> com.apple.AppleFSCompression.AppleFSCompressionTypeDataless 1.0.0d1
> 
> com.apple.BootCache 40
> 
> com.apple.AppleFSCompression.AppleFSCompressionTypeZlib 1.0.0
> 
> com.apple.AppleSystemPolicy 1.0
> 
> com.apple.driver.AppleVirtIO 2.1.3
> 
> com.apple.driver.AppleAHCIPort 329.260.5
> 
> com.apple.private.KextAudit 1.0
> 
> com.apple.driver.AppleACPIButtons 6.1
> 
> com.apple.driver.AppleRTC 2.0
> 
> com.apple.driver.AppleSMBIOS 2.1
> 
> com.apple.driver.AppleAPIC 1.7
> 
> com.apple.nke.applicationfirewall 201
> 
> com.apple.security.TMSafetyNet 8
> 
> com.apple.kext.AMDRadeonX4030HWLibs 1.0
> 
> com.apple.iokit.IOAcceleratorFamily2 404.14
> 
> com.apple.kext.AMDRadeonX4000HWServices 2.1.1
> 
> com.apple.driver.AppleGraphicsControl 3.50.12
> 
> com.apple.iokit.IOAVBFamily 760.6
> 
> com.apple.plugin.IOgPTPPlugin 740.2
> 
> com.apple.iokit.IOEthernetAVBController 1.1.0
> 
> com.apple.iokit.IOSkywalkFamily 1
> 
> com.apple.driver.AppleSSE 1.0
> 
> com.apple.iokit.IOSurface 255.6.1
> 
> com.apple.iokit.IOBluetoothFamily 6.0.14d3
> 
> com.apple.iokit.IONDRVSupport 530.51
> 
> com.apple.AppleGPUWrangler 3.50.12
> 
> com.apple.driver.AppleUSBAudio 315.6
> 
> com.apple.driver.AppleUSBHostMergeProperties 1.2
> 
> com.apple.driver.AppleHDAController 282.54
> 
> com.apple.iokit.IOHDAFamily 282.54
> 
> com.apple.iokit.IOAudioFamily 206.5
> 
> com.apple.vecLib.kext 1.2.0
> 
> com.apple.driver.AppleSMBusPCI 1.0.14d1
> 
> com.apple.kext.AMDSupport 2.1.1
> 
> com.apple.AppleGraphicsDeviceControl 3.50.12
> 
> com.apple.iokit.IOGraphicsFamily 530.66
> 
> com.apple.driver.IOPlatformPluginLegacy 1.0.0
> 
> com.apple.driver.IOPlatformPluginFamily 6.0.0d8
> 
> com.apple.iokit.IOSlowAdaptiveClockingFamily 1.0.0
> 
> com.apple.kext.triggers 1.0
> 
> com.apple.driver.usb.IOUSBHostHIDDevice 1.2
> 
> com.apple.driver.usb.cdc 5.0.0
> 
> com.apple.driver.usb.networking 5.0.0
> 
> com.apple.driver.usb.AppleUSBHostCompositeDevice 1.2
> 
> com.apple.driver.AppleXsanScheme 3
> 
> com.apple.filesystems.hfs.encodings.kext 1
> 
> com.apple.driver.usb.AppleUSBHostPacketFilter 1.0
> 
> com.apple.iokit.IOUSBFamily 900.4.2
> 
> com.apple.iokit.IOAHCIBlockStorage 301.270.1
> 
> com.apple.iokit.IOSerialFamily 11
> 
> com.apple.driver.usb.AppleUSBEHCIPCI 1.2
> 
> com.apple.iokit.IOAHCIFamily 288
> 
> com.apple.driver.usb.AppleUSBUHCIPCI 1.2
> 
> com.apple.driver.usb.AppleUSBUHCI 1.2
> 
> com.apple.driver.usb.AppleUSBEHCI 1.2
> 
> com.apple.driver.AppleEFINVRAM 2.1
> 
> com.apple.driver.AppleEFIRuntime 2.1
> 
> com.apple.iokit.IOHIDFamily 2.0.0
> 
> com.apple.security.quarantine 3
> 
> com.apple.security.sandbox 300.0
> 
> com.apple.kext.AppleMatch 1.0.0d1
> 
> com.apple.driver.DiskImages 493.0.0
> 
> com.apple.driver.AppleFDEKeyStore 28.30
> 
> com.apple.driver.AppleEffaceableStorage 1.0
> 
> com.apple.driver.AppleKeyStore 2
> 
> com.apple.driver.AppleUSBTDM 456.260.3
> 
> com.apple.driver.AppleMobileFileIntegrity 1.0.5
> 
> com.apple.iokit.IOUSBMassStorageDriver 145.200.2
> 
> com.apple.iokit.IOSCSIBlockCommandsDevice 408.250.3
> 
> com.apple.iokit.IOSCSIArchitectureModelFamily 408.250.3
> 
> com.apple.iokit.IOStorageFamily 2.1
> 
> com.apple.kext.CoreTrust 1
> 
> com.apple.driver.AppleCredentialManager 1.0
> 
> com.apple.driver.KernelRelayHost 1
> 
> com.apple.iokit.IOUSBHostFamily 1.2
> 
> com.apple.driver.usb.AppleUSBCommon 1.0
> 
> com.apple.driver.AppleBusPowerController 1.0
> 
> com.apple.driver.AppleSEPManager 1.0.1
> 
> com.apple.driver.IOSlaveProcessor 1
> 
> com.apple.iokit.IOTimeSyncFamily 740.2
> 
> com.apple.iokit.IONetworkingFamily 3.4
> 
> com.apple.iokit.IOReportFamily 47
> 
> com.apple.driver.AppleACPIPlatform 6.1
> 
> com.apple.driver.AppleSMC 3.1.9
> 
> com.apple.iokit.IOPCIFamily 2.9
> 
> com.apple.iokit.IOACPIFamily 1.4
> 
> com.apple.kec.pthread 1
> 
> com.apple.kec.Libm 1
> 
> com.apple.kec.corecrypto 1.0
> 
> 
> EOF
> 
> Model: iMac10,1, BootROM 213.0.0.0.0, 6 processors, Intel Core Solo, 3,19 GHz, 8 GB, SMC
> 
> Graphics: spdisplays_display, 10 MB
> 
> Memory Module: BANK 0/DIMM0, 8 GB, DDR3, 0 MHz, QEMU, unknown
> 
> Network Service: VMXNet3 Ethernet, Ethernet, en0
> 
> Serial ATA Device: QEMU HARDDISK, 85,9 GB
> 
> Serial ATA Device: QEMU HARDDISK, 268,4 MB
> 
> Serial ATA Device: QEMU HARDDISK, 2,14 GB
> 
> USB Device: USB 2.0 Bus
> 
> USB Device: QEMU USB Tablet
> 
> USB Device: QEMU USB Keyboard
> 
> USB Device: USB Bus
> 
> USB Device: USB Optical Mouse
> 
> USB Device: USB Bus
> 
> USB Device: USB Bus
> 
> USB Device: USB Keyboard
> 
> Thunderbolt Bus:

**Comment by kode54** [comment]
Try removing the virtual USB Tablet device?

**Comment by jcrowthe** [comment]
I am having this same issue with a Ryzen system and an RX 480. Did anyone find a solution?

**Comment by jcrowthe** [comment]
Ah, spoke ever so slightly too soon. Managed to find a configuration error. When passing through my RX 480 GPU to the VM, I also need to configure `-vga none` rather than `-vga qxl`. Final config looks like this:

```
qemu-system-x86_64 \
    -enable-kvm \
    -m $MEM \
    -machine q35,accel=kvm \
    -smp $CPUS \
    -cpu Penryn,vendor=GenuineIntel,kvm=on,+sse3,+sse4.2,+aes,+xsave,+avx,+xsaveopt,+xsavec,+xgetbv1,+avx2,+bmi2,+smep,+bmi1,+fma,+movbe,+invtsc \
    -device isa-applesmc,osk="$OSK" \
    -smbios type=2 \
    -drive if=pflash,format=raw,readonly,file="$OVMF/OVMF_CODE.fd" \
    -drive if=pflash,format=raw,file="$OVMF/OVMF_VARS-1024x768.fd" \
    -vga none \
    -usb -device usb-kbd -device usb-tablet \
    -netdev user,id=net0 \
    -device e1000-82545em,netdev=net0,id=net0,mac=52:54:00:0e:0d:20 \
    -device ich9-ahci,id=sata \
    -drive id=ESP,if=none,format=qcow2,file=ESP.qcow2 \
    -device ide-hd,bus=sata.2,drive=ESP \
    -drive id=SystemDisk,if=none,file="${SYSTEM_DISK}" \
    -device ide-hd,bus=sata.4,drive=SystemDisk \
    -device vfio-pci,host=09:00.0 \
    -device vfio-pci,host=09:00.1 \
    "${MOREARGS[@]}"
```

The two devices passed through our my RX480 and it's associated audio device. Hopefully this helps someone else running into this error.
