### ISSUE TITLE
Pick the qcow2 disk not reco

### ISSUE THREAD

**Issue by hostister** [foxlet/macOS-Simple-KVM#90]
Hello, i stuck in step 2. When i choose disk utility, can not pick this 32G qcow2 disk to install os. Why the system don't recognize it? I run the system with this script 
`./basic.sh drive id=SystemDisk,if=none,file=macos1.qcow2 device ide-hd,bus=sata.4,drive=SystemDisk`

https://imgur.com/a/lzVoyVO

Sorry for my english.

**Comment by foxlet** [comment]
You have to format it in Disk Utility first.

**Comment by hostister** [comment]
Ok, but how? Disk Utility don't show me the disk.

**Comment by BlackDragonDv** [comment]
basic.sh doesn't take argument so you can't add virtual disk this way. Edit basic.sh script and add virtual disk here. In README.md there is instruction for that (Step 2).

**Comment by foxlet** [comment]
Ah, yes, you have to edit the file, not pass arguments in the command line. Only `headless.sh` supports arguments.
