### ISSUE TITLE
Clover update

### ISSUE THREAD

**Issue by MingyaoLiu** [foxlet/macOS-Simple-KVM#95]
Hi,
I have installed macos KVM and everything is up and running, passthrough my gpu, network card and all working just fine.

However just have a question, is there a way to update clover? and how would that be?
It seems clover is pulled when running the installation script, and to me it seems to be installed in the ESP.qow2, however clover installer can't access that.
Thanks.

**Comment by kode54** [comment]
I'm not even sure this is even a good idea, other than to get kext injection working again. r5070 outright locks up on boot.

**Comment by MingyaoLiu** [comment]
> I'm not even sure this is even a good idea, other than to get kext injection working again. r5070 outright locks up on boot.

haha I c. Yah I ask this only because I made 2 kvm, one mojave one catalina, using the same repo here, however the 2 repo's clover are different, mojave is 1920? catalina is like 1965?

My catalina kvm run into critical issue, so I had to copy the ESP.qcow2 from my mojave kvm to have it boot.

Anyway this is basically why I was asking.

**Comment by foxlet** [comment]
Clover r5070 has been pushed to the repo.

**Comment by MingyaoLiu** [comment]
Cool I will try it out thx

**Comment by FrnchFrgg** [comment]
I tried to test it but the bootloader looks exactly the same, including the shown version that is 4920. Is it normal (because you somehow mixed the two to fix problems) or is there a mistake ? I did `git reset --hard` and even put away my `disk.qcow2` and created an empty one, to be certain it's not picking an old clover from elsewhere.

**Comment by kode54** [comment]
Did you duplicate your ESP.qcow2 and/or OVMF_* files around when installing the virtual machine? In my case, I have all the disk images duplicated into `/var/lib/libvirt/images`.

**Comment by foxlet** [comment]
You need to pull first before resetting, Clover is placed in `ESP.qcow2`.

**Comment by foxlet** [comment]
https://github.com/foxlet/macOS-Simple-KVM/blob/d126524413205e9924bb951c7930db687dce8e8e/ESP.qcow2?raw=true

**Comment by kode54** [comment]
I found the issue. OVMF is booting `/EFI/BOOT/BOOTX64.efi`, which is still 4920. The `/EFI/CLOVER/CLOVERX64.efi` is the correct version, but it's ignoring the `/startup.nsh` and booting the default boot binary instead.

**Comment by foxlet** [comment]
Ah, you're using non-stock vars.

**Comment by kode54** [comment]
I'm using a copy of the stock vars, which I copied to the `/var/lib/libvirt/qemu/nvram` directory, and renamed to `macOS_VARS.fd`

**Comment by FrnchFrgg** [comment]
I did "git fetch; git rebase; git reset --hard" so I should be safe on both `ESP.qcow2` and `firmware/OVMF_VARS-1024x768.fd`. My domain XML correctly has `<nvram>/path/to/git/repository/firmware/OVMF_VARS-1024x768.fd</nvram>` and `<source file='/path/to/git/repository/ESP.qcow2'/>`.
What did I miss ?

**Comment by foxlet** [comment]
Another update, please checkout `a226e378057d1440fcf49fb7ef9ff1055097bce5` "[ESP] Update Clover to r5070, refix BOOTX64.EFI."

**Comment by FrnchFrgg** [comment]
I can confirm this indeed works. Thank you.
